//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUMMY
    {
        public int DUMMY_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public string TXT { get; set; }
        public string TXT2 { get; set; }
        public string OK { get; set; }
    }
}
