//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class F100
    {
        public int F100_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<System.DateTime> FODT { get; set; }
        public string FNAVN { get; set; }
        public string ENAVN { get; set; }
        public string ADR1 { get; set; }
        public Nullable<int> POSTNR { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string FN5 { get; set; }
        public string STRIKA { get; set; }
        public string KYN { get; set; }
        public string EN5 { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string KOTA { get; set; }
        public string ENFO { get; set; }
        public Nullable<int> CPR { get; set; }
        public string MNAVN { get; set; }
        public Nullable<decimal> UPPHADD { get; set; }
        public string OPRET { get; set; }
        public string OPDAT { get; set; }
        public Nullable<int> OLD_NR { get; set; }
        public string ARSTAL { get; set; }
        public string NY_F_DATO { get; set; }
        public string FUNDET { get; set; }
        public string PRI { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public Nullable<int> REG_NR { get; set; }
        public Nullable<int> KONTO { get; set; }
        public Nullable<int> REG_NR_FF { get; set; }
        public Nullable<int> KONTO_FF { get; set; }
        public Nullable<System.DateTime> FLYT_DATO { get; set; }
        public Nullable<System.DateTime> KOYR_DATO { get; set; }
        public string ART { get; set; }
    
        public virtual LIMART LIMART { get; set; }
    }
}
