//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_TMP
    {
        public int FR_TMP_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<decimal> KR92_0 { get; set; }
        public Nullable<decimal> KR93_0 { get; set; }
        public Nullable<decimal> KR93_1 { get; set; }
        public Nullable<decimal> KR92_1 { get; set; }
    }
}
