//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_TOT
    {
        public int FRT_TOT_Id { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public Nullable<System.DateTime> FLYT_DATO { get; set; }
        public Nullable<decimal> UPPH_KR { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> UPPH_ELE { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> IN_LN { get; set; }
        public Nullable<System.DateTime> KOYR_DATO { get; set; }
        public string ART { get; set; }
        public Nullable<int> KOYR_DIV { get; set; }
        public Nullable<int> FRT_TOT_NR { get; set; }
    }
}
