//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOVD
    {
        public int HOVD_Id { get; set; }
        public string SKIP { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public Nullable<int> SKJAL_NR { get; set; }
        public string PAR_SKIP { get; set; }
        public Nullable<int> PAR_SKJAL { get; set; }
        public Nullable<decimal> MANTAL { get; set; }
        public Nullable<System.DateTime> PRIS_DATO { get; set; }
        public Nullable<System.DateTime> STUD_DATO { get; set; }
        public string AVR_STAD { get; set; }
        public string SKIP_ART { get; set; }
        public Nullable<System.DateTime> IND_DATO { get; set; }
        public string IND_HH { get; set; }
        public string IND_MM { get; set; }
        public string IND_ID { get; set; }
        public string STATUS { get; set; }
        public string UDSKREVET { get; set; }
        public string UPPTALD { get; set; }
        public Nullable<System.DateTime> UD_DATO { get; set; }
        public string UD_HH { get; set; }
        public string UD_MM { get; set; }
        public string UD_ID { get; set; }
        public Nullable<decimal> KG_IALT { get; set; }
        public Nullable<decimal> UPPH_IALT { get; set; }
        public Nullable<decimal> TIL_SKIP_PCT { get; set; }
        public Nullable<decimal> TIL_SKIP_KR { get; set; }
        public Nullable<decimal> TIL_MANN_PCT { get; set; }
        public Nullable<decimal> TIL_MANN_KR { get; set; }
        public Nullable<int> LOBNR { get; set; }
        public string VIDAR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> LN_IALT { get; set; }
    }
}
