//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOSY
    {
        public int INFOSYS_Id { get; set; }
        public string NAVN { get; set; }
        public string ADR_1 { get; set; }
        public string ADR_2 { get; set; }
        public string POSTNR { get; set; }
        public string TLF { get; set; }
        public string KONTO_1 { get; set; }
        public string KONTO_2 { get; set; }
        public string GIRO_1 { get; set; }
        public Nullable<System.DateTime> DAGSDATO { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    }
}
