//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEV
    {
        public int LEV_Id { get; set; }
        public Nullable<int> LEVNR { get; set; }
        public string LEVNAVN { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public Nullable<int> POSTNR { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public string TELEFON { get; set; }
        public string TELEFAX { get; set; }
        public string KONTAKT { get; set; }
        public string KONTAKT2 { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string NAVN5 { get; set; }
        public string ILUL { get; set; }
        public string NATJOB { get; set; }
        public Nullable<int> LN_IALT { get; set; }
    
        public virtual LIMART LIMART { get; set; }
    }
}
