//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMAGJ
    {
        public int LIMAGJ_Id { get; set; }
        public string LIMART { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public string ME_NUMMER { get; set; }
        public Nullable<int> FK_SKIB_Id { get; set; }
        public Nullable<int> ARSTAL { get; set; }
        public Nullable<decimal> BELOB { get; set; }
        public Nullable<System.DateTime> ING_DATO { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual LIMART LIMART1 { get; set; }
        public virtual SKIB SKIB { get; set; }
    }
}
