//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOYVIR
    {
        public int LOYVIR_Id { get; set; }
        public string PROG_ID { get; set; }
        public string PER_ID { get; set; }
        public string RUN_OK { get; set; }
        public string LES_OK { get; set; }
        public string SKRIV_OK { get; set; }
        public string DEL_OK { get; set; }
        public string KEY { get; set; }
        public string DAG_STAT { get; set; }
        public string FRA_HH { get; set; }
        public string FRA_MM { get; set; }
        public string TIL_HH { get; set; }
        public string TIL_MM { get; set; }
        public string FRA_HH1 { get; set; }
        public string FRA_MM1 { get; set; }
        public string TIL_HH1 { get; set; }
        public string TIL_MM1 { get; set; }
        public string LOG { get; set; }
        public Nullable<int> STROKE_TIME { get; set; }
        public string STROKE_CHK { get; set; }
    }
}
