//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANGLA
    {
        public int MANGLA_Id { get; set; }
        public Nullable<int> MI_NR { get; set; }
        public Nullable<System.DateTime> FRA { get; set; }
        public Nullable<System.DateTime> TIL { get; set; }
    }
}
