//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANNING
    {
        public int MANNING_Id { get; set; }
        public string LIMART { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public Nullable<int> ME_NUMMER { get; set; }
        public Nullable<System.DateTime> FODT { get; set; }
        public string TLF { get; set; }
        public string FOEN { get; set; }
        public string FNAVN { get; set; }
        public string MNAVN { get; set; }
        public string ENAVN { get; set; }
        public string ADR_1 { get; set; }
        public string ADR_2 { get; set; }
        public string POSTNR { get; set; }
        public Nullable<int> FK_TR_HOVD_Id { get; set; }
        public Nullable<int> POSTBOX { get; set; }
        public string KON { get; set; }
        public Nullable<int> BE_ME_NUMMER { get; set; }
        public string M_TYPE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string ARB_TYPE { get; set; }
        public Nullable<int> FK_LGJALD_Id { get; set; }
        public Nullable<int> CPR { get; set; }
        public Nullable<decimal> PCT_PART { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual LGJALD LGJALD { get; set; }
        public virtual LIMART LIMART1 { get; set; }
        public virtual TR_HOVD TR_HOVD { get; set; }
    }
}
