//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDAGAR
    {
        public int MDAGAR_Id { get; set; }
        public string AR { get; set; }
        public string TYPA { get; set; }
        public Nullable<decimal> DAGAR { get; set; }
        public Nullable<decimal> MANS { get; set; }
        public Nullable<decimal> IALT { get; set; }
    }
}
