//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MI2_HOVD
    {
        public int ID { get; set; }
        public Nullable<int> MI_NR { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public string SKIB_ID { get; set; }
        public string AR { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string SK_ID { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string ID_TUR { get; set; }
        public string STARV { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public Nullable<System.DateTime> FODT { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public int? MI_NRGR { get; set; }
        public int PERS_NRGR { get; set; }
        public int SK_NRGR { get; set; }
        public string STARV20 { get; set; }
        public int DAGAR_GR { get; set; }

        public int? MemberNR { get; set; }
        public int? ReidariId { get; set; }
        public string SkipId { get; set; }
        public int? TR_HOVD_PostNr { get; set; }
        public int? StarvId { get; set; }
        public int? StatId { get; set; }
        public string TypaId { get; set; }
        public int? PostNrPostNr { get; set; }
        public string CompanyId { get; set; }
        public string MemberTypeCode { get; set; }
    }
}