//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNUR
    {
        public int MUNUR_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<decimal> KR_OK { get; set; }
        public Nullable<decimal> KR_NOT_OK { get; set; }
    }
}
