//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class P1_NOT
    {
        public int P1_NOT_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public Nullable<int> PAGE { get; set; }
        public Nullable<int> LAST_USED_LIN { get; set; }
        public string L01 { get; set; }
        public string L02 { get; set; }
        public string L03 { get; set; }
        public string L04 { get; set; }
        public string L05 { get; set; }
        public string L06 { get; set; }
        public string L07 { get; set; }
        public string L08 { get; set; }
        public string L09 { get; set; }
        public string L10 { get; set; }
        public string L11 { get; set; }
        public string L12 { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
