//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class P2000
    {
        public int P2000_Id { get; set; }
        public string ID_FF { get; set; }
        public string NAVN { get; set; }
        public string ID_GR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
    }
}
