//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSORD
    {
        public int PASSORD_Id { get; set; }
        public string PASSORD1 { get; set; }
        public string PR_NAME { get; set; }
        public Nullable<int> PAGEEND { get; set; }
        public Nullable<int> FORMFEED { get; set; }
        public string L_PR_NAME { get; set; }
        public Nullable<int> L_FORMFEED { get; set; }
        public Nullable<int> L_PAGEEND { get; set; }
        public Nullable<int> L_PNR { get; set; }
        public Nullable<int> F_PNR { get; set; }
        public string AKTIV { get; set; }
        public Nullable<System.DateTime> LOGIN_DATO { get; set; }
        public string LOGIN_HH { get; set; }
        public string LOGIN_MM { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> PRI_OWN { get; set; }
        public Nullable<int> PRI_GRP { get; set; }
        public Nullable<int> CONV { get; set; }
        public string CHK_KAL { get; set; }
        public string LOYNA1 { get; set; }
        public string LOYND2 { get; set; }
        public string RENS_OK { get; set; }
        public Nullable<int> TRIAL { get; set; }
        public string LOYNA2 { get; set; }
        public string TYPA { get; set; }
        public string PR_DEV { get; set; }
        public string LPR_DEV { get; set; }
        public string LOG { get; set; }
        public Nullable<System.DateTime> LOGOUT_DATO { get; set; }
        public string LOGOUT_HH { get; set; }
        public string LOGOUT_MM { get; set; }
        public Nullable<int> SESSION_NOW_MM { get; set; }
        public Nullable<int> SESSION_TOT_MM { get; set; }
    }
}
