//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDER
    {
        public int REMINDER_Id { get; set; }
        public Nullable<System.DateTime> DATO { get; set; }
        public Nullable<int> NR { get; set; }
        public string JN { get; set; }
        public Nullable<int> ANT { get; set; }
        public Nullable<System.DateTime> UTDATO { get; set; }
        public string ER_P { get; set; }
        public Nullable<System.DateTime> AVM_DATO { get; set; }
        public string AVM_ID { get; set; }
        public Nullable<int> DAGAR { get; set; }
        public string BRV_OK { get; set; }
        public string KOTA { get; set; }
    }
}
