//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIBMAN
    {
        public int SKIBMAN_Id { get; set; }
        public Nullable<int> ME_NUMMER { get; set; }
        public Nullable<int> FK_SKIB_Id { get; set; }
        public Nullable<int> ARSTAL { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public string SKIBS_KODE { get; set; }
        public string SKIBS_NAVN { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public Nullable<int> RET_HH { get; set; }
        public Nullable<int> RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual SKIB SKIB { get; set; }
    }
}
