//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIPTYPE
    {
        public SKIPTYPE()
        {
            this.SKIPs = new HashSet<SKIP>();
            this.TURHEADs = new HashSet<TURHEAD>();
        }
    
        public int SKIPTYPE_Id { get; set; }
        public string SK_TYPE { get; set; }
        public string SK_TEKST { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual ICollection<SKIP> SKIPs { get; set; }
        public virtual ICollection<TURHEAD> TURHEADs { get; set; }
    }
}
