//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKOTA
    {
        public int SKOTA_Id { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public string AR { get; set; }
        public string STARV { get; set; }
        public Nullable<int> LOBNR { get; set; }
        public Nullable<int> ANT { get; set; }
    }
}
