//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLF_TMP
    {
        public int TLF_TMP_Id { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public string SKIB_ID { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<int> MI_NR { get; set; }
        public Nullable<int> INX { get; set; }
        public Nullable<int> DAGE { get; set; }
    }
}
