//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BYTI
    {
        public int TMP_BYTI_Id { get; set; }
        public string RAD { get; set; }
        public Nullable<decimal> F0 { get; set; }
        public Nullable<decimal> F1 { get; set; }
        public Nullable<decimal> F2 { get; set; }
        public Nullable<decimal> F3 { get; set; }
        public Nullable<decimal> F4 { get; set; }
        public Nullable<decimal> F5 { get; set; }
        public Nullable<decimal> F6 { get; set; }
        public Nullable<decimal> F7 { get; set; }
        public Nullable<decimal> F8 { get; set; }
        public Nullable<decimal> F9 { get; set; }
        public Nullable<decimal> F10 { get; set; }
        public Nullable<decimal> F11 { get; set; }
        public Nullable<decimal> F12 { get; set; }
        public Nullable<decimal> F13 { get; set; }
        public Nullable<decimal> P0 { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P2 { get; set; }
        public Nullable<decimal> P3 { get; set; }
        public Nullable<decimal> P4 { get; set; }
        public Nullable<decimal> P5 { get; set; }
        public Nullable<decimal> P6 { get; set; }
        public Nullable<decimal> P7 { get; set; }
        public Nullable<decimal> P8 { get; set; }
        public Nullable<decimal> P9 { get; set; }
        public Nullable<decimal> P10 { get; set; }
        public Nullable<decimal> P11 { get; set; }
        public Nullable<decimal> P12 { get; set; }
        public Nullable<decimal> P13 { get; set; }
    }
}
