//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_UTS
    {
        public int TMP_UTS_Id { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public Nullable<System.DateTime> UD_DATO { get; set; }
        public string UD_HH { get; set; }
        public string UD_MM { get; set; }
        public string UD_ID { get; set; }
        public string STAT { get; set; }
    }
}
