//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// No data in DB or found in any FRM file
    /// </summary>
    public partial class MA_LINE
    {
        public int MA_LINE_Id { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public Nullable<int> FK_TR_HOVD_Id { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public Nullable<decimal> PARTAR { get; set; }
        public Nullable<decimal> KR { get; set; }
        public Nullable<decimal> TILLAG1 { get; set; }
        public Nullable<decimal> TILLAG2 { get; set; }
        public Nullable<decimal> FRADRATT1 { get; set; }
        public Nullable<decimal> KR_IALT { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public string SKIB_ID { get; set; }
    
        public virtual Member P100 { get; set; }
        public virtual TR_HOVD TR_HOVD { get; set; }
    }
}
