//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESS
    {
        public int ADRESS_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public string FNAVN { get; set; }
        public string ENAVN { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
