//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMA
    {
        public int FIRMA_Id { get; set; }
        public string NAVN { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public string ADR3 { get; set; }
        public Nullable<int> ORDNR { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public Nullable<int> SKJAL_NR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string RENS_OK { get; set; }
        public Nullable<int> AVIS_NR { get; set; }
        public string FF { get; set; }
        public Nullable<int> FORELDNR { get; set; }
        public Nullable<int> FRI_MIN { get; set; }
        public Nullable<int> UDSKR_NR { get; set; }
        public string CHK_KALL { get; set; }
        public Nullable<int> KOYR_NR { get; set; }
        public string UD_OK { get; set; }
        public Nullable<int> NAT_ADD { get; set; }
        public Nullable<int> BARN { get; set; }
        public Nullable<int> LARARANR { get; set; }
        public Nullable<int> GREIN_NR { get; set; }
        public string OP_SYS { get; set; }
        public Nullable<int> STROKE_TIME { get; set; }
        public Nullable<int> JOB_NR { get; set; }
        public string OPR_LOG { get; set; }
        public Nullable<int> MI_NR { get; set; }
        public Nullable<int> LG_NR { get; set; }
        public string VIS_BETALER { get; set; }
        public Nullable<int> S_SEKUND { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public Nullable<int> TRP_NR { get; set; }
        public Nullable<int> FRT_NR { get; set; }
        public Nullable<int> A_TAL_LG { get; set; }
        public string LJG_VID { get; set; }
        public Nullable<int> FRT_TOT_NR { get; set; }
        public Nullable<int> LO_NR { get; set; }
        public Nullable<int> F_REG { get; set; }
        public Nullable<int> F_KTO { get; set; }
        public Nullable<decimal> F_PCT { get; set; }
        public string DIRT { get; set; }
        public string DIRT2 { get; set; }
    }
}
