//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class frt_lon7
    {
        public int frt_lon7_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public string AR { get; set; }
        public Nullable<decimal> FRTLON { get; set; }
        public Nullable<decimal> TRSP { get; set; }
        public Nullable<System.DateTime> FRT_DATO { get; set; }
        public Nullable<System.DateTime> TRS_DATO { get; set; }
        public Nullable<decimal> LO_KR_A { get; set; }
        public Nullable<decimal> LO_KR_F { get; set; }
        public Nullable<decimal> LO_KR_FRT { get; set; }
        public Nullable<System.DateTime> LO_DATO { get; set; }
        public Nullable<int> DG_AR { get; set; }
        public Nullable<int> TU_AR { get; set; }
        public Nullable<System.DateTime> DATO_AR { get; set; }
        public string ID_AR { get; set; }
        public Nullable<decimal> SAML_KR { get; set; }
        public Nullable<decimal> SAML_KR2 { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
