//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIB
    {
        public SKIB()
        {
            this.LIMAGJs = new HashSet<LIMAGJ>();
            this.LO_HOVD = new HashSet<LO_HOVD>();
            this.MI_HOVD = new HashSet<MI_HOVD>();
            this.MI2_HOVD = new HashSet<MI2_HOVD>();
            this.SKIBMen = new HashSet<SKIBMAN>();
            this.STXTs = new HashSet<STXT>();
            this.TR_HOVD = new HashSet<TR_HOVD>();
        }
    
        public int SKIB_Id { get; set; }
        public string NAVN { get; set; }
        public string ADR1 { get; set; }
        public string ADR2 { get; set; }
        public Nullable<int> POSTNR { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public string TELEFON { get; set; }
        public string TELEFAX { get; set; }
        public string KONTAKT { get; set; }
        public string KONTAKT2 { get; set; }
        public Nullable<System.DateTime> IND_REG { get; set; }
        public Nullable<System.DateTime> UD_REG { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string NAVN5 { get; set; }
        public string ILUL { get; set; }
        public Nullable<int> LN_IALT { get; set; }
        public string SK_TYPA { get; set; }
        public Nullable<int> REDERI { get; set; }
        public Nullable<int> FK_REIDARI_Id { get; set; }
        public Nullable<decimal> TONNAGE { get; set; }
        public Nullable<decimal> HK { get; set; }
        public Nullable<int> TXT_LN_IALT { get; set; }
    
        public virtual ICollection<LIMAGJ> LIMAGJs { get; set; }
        public virtual LIMART LIMART { get; set; }
        public virtual ICollection<LO_HOVD> LO_HOVD { get; set; }
        public virtual ICollection<MI_HOVD> MI_HOVD { get; set; }
        public virtual ICollection<MI2_HOVD> MI2_HOVD { get; set; }
        public virtual REIDARI REIDARI { get; set; }
        public virtual ICollection<SKIBMAN> SKIBMen { get; set; }
        public virtual ICollection<STXT> STXTs { get; set; }
        public virtual ICollection<TR_HOVD> TR_HOVD { get; set; }
    }
}
