//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class STXSK
    {
        public int STXSK_Id { get; set; }
        public string ST_ID { get; set; }
        public Nullable<int> FK_STARV_Id { get; set; }
        public string SK_ID { get; set; }
        public Nullable<int> FK_TYPA_Id { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public Nullable<decimal> PCT_PART { get; set; }
        public Nullable<decimal> TILLAG { get; set; }
        public Nullable<decimal> LGJALD { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual STARV STARV { get; set; }
        public virtual TYPA TYPA { get; set; }
    }
}
