//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURHEAD
    {
        public TURHEAD()
        {
            this.G100 = new HashSet<G100>();
            this.P100 = new HashSet<Member>();
            this.P200 = new HashSet<P200>();
            this.P300 = new HashSet<P300>();
            this.SBs = new HashSet<SB>();
        }
    
        public int TURHEAD_Id { get; set; }
        public string SK_NUMMER { get; set; }
        public Nullable<int> FK_SKIP_Id { get; set; }
        public Nullable<System.DateTime> TUR_START { get; set; }
        public Nullable<System.DateTime> TUR_SLUT { get; set; }
        public string PAR_SK_NUMMER { get; set; }
        public Nullable<decimal> MANTAL { get; set; }
        public string PRIS_DATO { get; set; }
        public Nullable<int> FK_STARV_Id { get; set; }
        public string STUD_DATO { get; set; }
        public Nullable<int> FK_STUDDATO_Id { get; set; }
        public string AVR_STED { get; set; }
        public string SK_TYPE { get; set; }
        public Nullable<int> FK_SKIPTYPE_Id { get; set; }
        public string INCL_AAR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual ICollection<G100> G100 { get; set; }
        public virtual ICollection<Member> P100 { get; set; }
        public virtual ICollection<P200> P200 { get; set; }
        public virtual ICollection<P300> P300 { get; set; }
        public virtual ICollection<SB> SBs { get; set; }
        public virtual SKIP SKIP { get; set; }
        public virtual SKIPTYPE SKIPTYPE { get; set; }
        public virtual STARV STARV { get; set; }
        public virtual STUDDATO STUDDATO { get; set; }
    }
}
