// <auto-generated />
namespace BootstrapWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Renamed_Trip_MANNING_I_to_CrewIncludingStayingAtHome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamed_Trip_MANNING_I_to_CrewIncludingStayingAtHome));
        
        string IMigrationMetadata.Id
        {
            get { return "201503061136301_Renamed_Trip_MANNING_I_to_CrewIncludingStayingAtHome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
