//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lundin_fff_alkaEntities : DbContext
    {
        public lundin_fff_alkaEntities()
            : base("name=lundin_fff_alkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ar> Ar { get; set; }
        public virtual DbSet<avgrgjaldsbolkur> avgrgjaldsbolkur { get; set; }
        public virtual DbSet<BokDim> BokDim { get; set; }
        public virtual DbSet<Bokingar> Bokingar { get; set; }
        public virtual DbSet<boktekstir> boktekstir { get; set; }
        public virtual DbSet<BokUpp> BokUpp { get; set; }
        public virtual DbSet<budget> budget { get; set; }
        public virtual DbSet<budgetkonto> budgetkonto { get; set; }
        public virtual DbSet<Dimensionir> Dimensionir { get; set; }
        public virtual DbSet<dk> dk { get; set; }
        public virtual DbSet<eindir> eindir { get; set; }
        public virtual DbSet<emaillog> emaillog { get; set; }
        public virtual DbSet<gjaldoyra> gjaldoyra { get; set; }
        public virtual DbSet<heimabankidef> heimabankidef { get; set; }
        public virtual DbSet<hopflyting> hopflyting { get; set; }
        public virtual DbSet<ilog> ilog { get; set; }
        public virtual DbSet<infoflow_afdelinger> infoflow_afdelinger { get; set; }
        public virtual DbSet<infoflow_indkob> infoflow_indkob { get; set; }
        public virtual DbSet<iusers> iusers { get; set; }
        public virtual DbSet<kontofeltdef> kontofeltdef { get; set; }
        public virtual DbSet<kontoflokkur> kontoflokkur { get; set; }
        public virtual DbSet<Kontolisti> Kontolisti { get; set; }
        public virtual DbSet<KontoVidmerking> KontoVidmerking { get; set; }
        public virtual DbSet<MemoStore> MemoStore { get; set; }
        public virtual DbSet<MvgTypa> MvgTypa { get; set; }
        public virtual DbSet<mvgundantok> mvgundantok { get; set; }
        public virtual DbSet<rel_bok_infoflow> rel_bok_infoflow { get; set; }
        public virtual DbSet<rel_iusers_dimensionir> rel_iusers_dimensionir { get; set; }
        public virtual DbSet<rel_iusers_konto> rel_iusers_konto { get; set; }
        public virtual DbSet<rel_konto_felt> rel_konto_felt { get; set; }
        public virtual DbSet<rel_konto_flokkar> rel_konto_flokkar { get; set; }
        public virtual DbSet<rentubolkur> rentubolkur { get; set; }
        public virtual DbSet<rokn_columncombination> rokn_columncombination { get; set; }
        public virtual DbSet<rokn_dim> rokn_dim { get; set; }
        public virtual DbSet<rokn_dimAnrOr> rokn_dimAnrOr { get; set; }
        public virtual DbSet<rokn_formulaelement> rokn_formulaelement { get; set; }
        public virtual DbSet<rokn_grundtol> rokn_grundtol { get; set; }
        public virtual DbSet<rokn_kontogruppa> rokn_kontogruppa { get; set; }
        public virtual DbSet<rokn_kontogruppalinjir> rokn_kontogruppalinjir { get; set; }
        public virtual DbSet<rokn_lyklatol> rokn_lyklatol { get; set; }
        public virtual DbSet<rokn_reports> rokn_reports { get; set; }
        public virtual DbSet<rokn_reportsColumnCombination> rokn_reportsColumnCombination { get; set; }
        public virtual DbSet<rokn_reportsLines> rokn_reportsLines { get; set; }
        public virtual DbSet<rokn_reportsUsers> rokn_reportsUsers { get; set; }
        public virtual DbSet<rokn_slag> rokn_slag { get; set; }
        public virtual DbSet<rokn_uppseting> rokn_uppseting { get; set; }
        public virtual DbSet<rokn_uppsetingprbrukara> rokn_uppsetingprbrukara { get; set; }
        public virtual DbSet<ryk_aldur_linjur> ryk_aldur_linjur { get; set; }
        public virtual DbSet<Ryk_aldur_ryk> Ryk_aldur_ryk { get; set; }
        public virtual DbSet<Ryk_aldur_tmp> Ryk_aldur_tmp { get; set; }
        public virtual DbSet<Ryk_koyring> Ryk_koyring { get; set; }
        public virtual DbSet<Ryk_rykkjarar> Ryk_rykkjarar { get; set; }
        public virtual DbSet<Saldolisti> Saldolisti { get; set; }
        public virtual DbSet<skuffukonto> skuffukonto { get; set; }
        public virtual DbSet<skuffur> skuffur { get; set; }
        public virtual DbSet<skuffurusers> skuffurusers { get; set; }
        public virtual DbSet<SMAvgreidsluhovd> SMAvgreidsluhovd { get; set; }
        public virtual DbSet<SMAvgreidslulinjur> SMAvgreidslulinjur { get; set; }
        public virtual DbSet<SMBotntekstir> SMBotntekstir { get; set; }
        public virtual DbSet<SMGjaldshattur> SMGjaldshattur { get; set; }
        public virtual DbSet<SMGjaldstreyt> SMGjaldstreyt { get; set; }
        public virtual DbSet<SMKassauppteljing> SMKassauppteljing { get; set; }
        public virtual DbSet<SMKassi> SMKassi { get; set; }
        public virtual DbSet<SMNummarseriur> SMNummarseriur { get; set; }
        public virtual DbSet<SMSedlahovd> SMSedlahovd { get; set; }
        public virtual DbSet<SMSedlalinjur> SMSedlalinjur { get; set; }
        public virtual DbSet<SMVorubolkur> SMVorubolkur { get; set; }
        public virtual DbSet<SMVorur> SMVorur { get; set; }
        public virtual DbSet<sqlversion> sqlversion { get; set; }
        public virtual DbSet<subskjol> subskjol { get; set; }
        public virtual DbSet<tekstbokdef> tekstbokdef { get; set; }
        public virtual DbSet<Tidarskeid> Tidarskeid { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<variablar> variablar { get; set; }
        public virtual DbSet<web_variablar> web_variablar { get; set; }
        public virtual DbSet<rokn_lykla_tmp> rokn_lykla_tmp { get; set; }
        public virtual DbSet<rokn_roknskapartol> rokn_roknskapartol { get; set; }
        public virtual DbSet<tmp_roknskapartol> tmp_roknskapartol { get; set; }
    }
}
