//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ar()
        {
            this.Saldolisti = new HashSet<Saldolisti>();
            this.Tidarskeid = new HashSet<Tidarskeid>();
        }
    
        public int ArId { get; set; }
        public System.DateTime FraDato { get; set; }
        public System.DateTime TilDato { get; set; }
        public string Vidmerking { get; set; }
        public int arsnr { get; set; }
        public bool enda { get; set; }
        public byte[] rv { get; set; }
        public string PathDocuments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saldolisti> Saldolisti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tidarskeid> Tidarskeid { get; set; }
    }
}
