//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BokDim
    {
        public int BokDimId { get; set; }
        public System.DateTime dato { get; set; }
        public int bokid { get; set; }
        public int dimnr { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> TidarskeidId { get; set; }
        public Nullable<int> DimensionirId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Bokingar Bokingar { get; set; }
        public virtual Dimensionir Dimensionir { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual Tidarskeid Tidarskeid { get; set; }
    }
}
