//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bokingar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bokingar()
        {
            this.BokDim = new HashSet<BokDim>();
            this.rel_bok_infoflow = new HashSet<rel_bok_infoflow>();
            this.Ryk_aldur_ryk = new HashSet<Ryk_aldur_ryk>();
        }
    
        public int BokID { get; set; }
        public System.DateTime Dato { get; set; }
        public int Skjal { get; set; }
        public decimal Upphadd { get; set; }
        public string Tekstur { get; set; }
        public System.DateTime DatoReelt { get; set; }
        public System.TimeSpan Klokka { get; set; }
        public Nullable<decimal> Valuta { get; set; }
        public Nullable<decimal> Hagtol { get; set; }
        public bool Fjala { get; set; }
        public Nullable<int> HeimaBanki { get; set; }
        public string HeimaBankaKonto { get; set; }
        public Nullable<int> SubSkjal { get; set; }
        public int BokingarSlag { get; set; }
        public Nullable<int> DebitKontolistiId { get; set; }
        public Nullable<int> KreditKontolistiId { get; set; }
        public Nullable<int> TidarskeidId { get; set; }
        public Nullable<int> SkuffurId { get; set; }
        public Nullable<int> UpprunaSkuffurId { get; set; }
        public Nullable<int> UsersId { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> KreditKontoNummar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokDim> BokDim { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual Kontolisti Kontolisti1 { get; set; }
        public virtual skuffur skuffur { get; set; }
        public virtual subskjol subskjol { get; set; }
        public virtual Tidarskeid Tidarskeid { get; set; }
        public virtual skuffur skuffur1 { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_bok_infoflow> rel_bok_infoflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ryk_aldur_ryk> Ryk_aldur_ryk { get; set; }
    }
}
