//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class boktekstir
    {
        public int BokTekstirId { get; set; }
        public int keycode { get; set; }
        public string keycodetext { get; set; }
        public string tekstur { get; set; }
        public int isuserdefined { get; set; }
        public byte[] rv { get; set; }
    }
}
