//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BokUpp
    {
        public int BokUppId { get; set; }
        public int FirmaNr { get; set; }
        public string Navn { get; set; }
        public string Bustadur { get; set; }
        public string Bustadur2 { get; set; }
        public string Bustadur3 { get; set; }
        public Nullable<int> Tidarskipan { get; set; }
        public Nullable<System.DateTime> PrimoDatoRoknAr { get; set; }
        public Nullable<int> VerandiRoknAr { get; set; }
        public bool Kontoflokkar { get; set; }
        public Nullable<int> Konv_InsertKonti { get; set; }
        public Nullable<int> Konv_InsertSaldi { get; set; }
        public bool Dim1 { get; set; }
        public bool Dim2 { get; set; }
        public bool Dim3 { get; set; }
        public bool Dim4 { get; set; }
        public bool Dim5 { get; set; }
        public bool OgnarKartotek { get; set; }
        public bool Valuta { get; set; }
        public bool Hagtol { get; set; }
        public bool Skuffur { get; set; }
        public string Dim1Navn { get; set; }
        public string Dim2Navn { get; set; }
        public string Dim3Navn { get; set; }
        public string Dim4Navn { get; set; }
        public string Dim5Navn { get; set; }
        public string OgnarKartotekNavn { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string heimasida { get; set; }
        public string LeidTilTekstbokingar { get; set; }
        public Nullable<decimal> rb_satsur { get; set; }
        public Nullable<decimal> rentaavrundasttilkronur { get; set; }
        public Nullable<decimal> rentaminkronur { get; set; }
        public Nullable<decimal> rentaumsitingargjaldkronur { get; set; }
        public string leidtilheimabanka { get; set; }
        public Nullable<int> ScanTeljari { get; set; }
        public string leidtilskjol { get; set; }
        public string leidtillogo { get; set; }
        public string banknavn1 { get; set; }
        public string banknavn2 { get; set; }
        public string banknavn3 { get; set; }
        public string banknavn4 { get; set; }
        public string banknavn5 { get; set; }
        public string bankkontonr1 { get; set; }
        public string bankkontonr2 { get; set; }
        public string bankkontonr3 { get; set; }
        public string bankkontonr4 { get; set; }
        public string bankkontonr5 { get; set; }
        public Nullable<decimal> ryk_procentsaldo { get; set; }
        public string infoflow_connectionstring { get; set; }
        public string infoflow_password { get; set; }
        public int infoflow_enable { get; set; }
        public decimal ag_kontoavrit_satsur { get; set; }
        public decimal ag_faktura_satsur { get; set; }
        public string ag_kontoavrit_boktekstur { get; set; }
        public string ag_faktura_boktekstur { get; set; }
        public Nullable<int> VerandiTidarskeidId { get; set; }
        public Nullable<int> NullBokingKontolistiId { get; set; }
        public Nullable<int> KonvInsertKontolistiId { get; set; }
        public Nullable<int> ClearingKontolistiId { get; set; }
        public Nullable<int> MvgClearingKontolistiId { get; set; }
        public Nullable<int> RentaKontolistiId { get; set; }
        public Nullable<int> SildberinSkuffurId { get; set; }
        public Nullable<int> RykSkuffurId { get; set; }
        public Nullable<int> RykRaksturKontolistiId { get; set; }
        public Nullable<int> RykKontoflokkurId { get; set; }
        public Nullable<int> RykInkassoKontoflokkurId { get; set; }
        public Nullable<int> InfoflowSkuffurId { get; set; }
        public Nullable<int> InfoflowKontolistiId { get; set; }
        public Nullable<int> AgKontoavritKontolistiId { get; set; }
        public Nullable<int> AgFakturaKontolistiId { get; set; }
        public Nullable<int> AgSkuffurId { get; set; }
        public byte[] rv { get; set; }
        public string PathToDbBackup { get; set; }
        public string Finr { get; set; }
        public string LeidTilOioxml { get; set; }
    
        public virtual kontoflokkur kontoflokkur { get; set; }
        public virtual kontoflokkur kontoflokkur1 { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual Kontolisti Kontolisti1 { get; set; }
        public virtual Kontolisti Kontolisti2 { get; set; }
        public virtual Kontolisti Kontolisti3 { get; set; }
        public virtual Kontolisti Kontolisti4 { get; set; }
        public virtual Kontolisti Kontolisti5 { get; set; }
        public virtual Kontolisti Kontolisti6 { get; set; }
        public virtual Kontolisti Kontolisti7 { get; set; }
        public virtual Kontolisti Kontolisti8 { get; set; }
        public virtual skuffur skuffur1 { get; set; }
        public virtual skuffur skuffur2 { get; set; }
        public virtual skuffur skuffur3 { get; set; }
        public virtual skuffur skuffur4 { get; set; }
        public virtual Tidarskeid Tidarskeid { get; set; }
    }
}
