//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public budget()
        {
            this.budgetkonto = new HashSet<budgetkonto>();
            this.rokn_reportsLines = new HashSet<rokn_reportsLines>();
        }
    
        public int BudgetId { get; set; }
        public int arsnr { get; set; }
        public int version { get; set; }
        public string vidmerking { get; set; }
        public int dimnr { get; set; }
        public Nullable<int> SmbArId { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budgetkonto> budgetkonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_reportsLines> rokn_reportsLines { get; set; }
    }
}
