//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class budgetkonto
    {
        public int BudgetKontoId { get; set; }
        public decimal m1 { get; set; }
        public decimal m2 { get; set; }
        public decimal m3 { get; set; }
        public decimal m4 { get; set; }
        public decimal m5 { get; set; }
        public decimal m6 { get; set; }
        public decimal m7 { get; set; }
        public decimal m8 { get; set; }
        public decimal m9 { get; set; }
        public decimal m10 { get; set; }
        public decimal m11 { get; set; }
        public decimal m12 { get; set; }
        public Nullable<decimal> samladupphadd { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> DimensionirId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual budget budget { get; set; }
        public virtual Dimensionir Dimensionir { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
    }
}
