//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimensionir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dimensionir()
        {
            this.BokDim = new HashSet<BokDim>();
            this.budgetkonto = new HashSet<budgetkonto>();
            this.mvgundantok = new HashSet<mvgundantok>();
            this.rel_iusers_dimensionir = new HashSet<rel_iusers_dimensionir>();
            this.rokn_dim = new HashSet<rokn_dim>();
            this.SMKassi = new HashSet<SMKassi>();
            this.SMKassi1 = new HashSet<SMKassi>();
            this.SMKassi2 = new HashSet<SMKassi>();
            this.SMKassi3 = new HashSet<SMKassi>();
            this.SMKassi4 = new HashSet<SMKassi>();
            this.SMSedlalinjur = new HashSet<SMSedlalinjur>();
            this.SMSedlalinjur1 = new HashSet<SMSedlalinjur>();
            this.SMSedlalinjur2 = new HashSet<SMSedlalinjur>();
            this.SMSedlalinjur3 = new HashSet<SMSedlalinjur>();
            this.SMSedlalinjur4 = new HashSet<SMSedlalinjur>();
        }
    
        public int DimensionirId { get; set; }
        public string Kota { get; set; }
        public Nullable<int> DimNr { get; set; }
        public string Fragreiding { get; set; }
        public Nullable<decimal> Avskriving { get; set; }
        public string Stad { get; set; }
        public string stytting { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokDim> BokDim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budgetkonto> budgetkonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvgundantok> mvgundantok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_iusers_dimensionir> rel_iusers_dimensionir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_dim> rokn_dim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassi> SMKassi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassi> SMKassi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassi> SMKassi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassi> SMKassi3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassi> SMKassi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur4 { get; set; }
    }
}
