//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class heimabankidef
    {
        public int HeimaBankiDefId { get; set; }
        public string navn { get; set; }
        public string slag { get; set; }
        public string pathheimabanki { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public string tekstur { get; set; }
        public int SkuffurId { get; set; }
        public int KontolistiId { get; set; }
        public Nullable<int> ClearingKontolistiId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual skuffur skuffur { get; set; }
    }
}
