//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hopflyting
    {
        public int HopflytingId { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public Nullable<decimal> upphadd { get; set; }
        public Nullable<int> bankaregnr { get; set; }
        public string bankakonto { get; set; }
        public string tekstur1 { get; set; }
        public string tekstur2 { get; set; }
        public string tekstur3 { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual users users { get; set; }
    }
}
