//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilog
    {
        public int ilo_id { get; set; }
        public System.DateTime dagur { get; set; }
        public System.TimeSpan klokkan { get; set; }
        public string ipadressa { get; set; }
        public Nullable<int> IUsersId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual iusers iusers { get; set; }
    }
}
