//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class iusers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iusers()
        {
            this.ilog = new HashSet<ilog>();
            this.rel_iusers_dimensionir = new HashSet<rel_iusers_dimensionir>();
            this.rel_iusers_konto = new HashSet<rel_iusers_konto>();
            this.web_variablar = new HashSet<web_variablar>();
        }
    
        public int IUsersId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int loyvi { get; set; }
        public string navn { get; set; }
        public bool sperradur { get; set; }
        public bool changepassword { get; set; }
        public System.DateTime passwordtimestamp { get; set; }
        public int failedlogins { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilog> ilog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_iusers_dimensionir> rel_iusers_dimensionir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rel_iusers_konto> rel_iusers_konto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<web_variablar> web_variablar { get; set; }
    }
}
