//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoStore
    {
        public int Id { get; set; }
        public string TabellNavn { get; set; }
        public string Lykil1 { get; set; }
        public string Lykil2 { get; set; }
        public int Slag { get; set; }
        public Nullable<System.DateTime> Dagfesting { get; set; }
        public string UserId { get; set; }
        public string Vidmerkingar { get; set; }
        public string FilKelda { get; set; }
        public string FilNavn { get; set; }
        public string Extension { get; set; }
        public string Memo { get; set; }
    }
}
