//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MvgTypa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MvgTypa()
        {
            this.Kontolisti = new HashSet<Kontolisti>();
            this.mvgundantok = new HashSet<mvgundantok>();
            this.mvgundantok1 = new HashSet<mvgundantok>();
            this.SMVorubolkur = new HashSet<SMVorubolkur>();
            this.SMVorubolkur1 = new HashSet<SMVorubolkur>();
        }
    
        public int MvgTypaId { get; set; }
        public int Nummar { get; set; }
        public decimal Satsur { get; set; }
        public string Slag { get; set; }
        public string Vidmerking { get; set; }
        public Nullable<decimal> minusmvg { get; set; }
        public int bokslag { get; set; }
        public Nullable<decimal> minusmvg2 { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> MinusKontolistiId { get; set; }
        public Nullable<int> StatusKontolistiId { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontolisti> Kontolisti { get; set; }
        public virtual Kontolisti Kontolisti1 { get; set; }
        public virtual Kontolisti Kontolisti2 { get; set; }
        public virtual Kontolisti Kontolisti3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvgundantok> mvgundantok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvgundantok> mvgundantok1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMVorubolkur> SMVorubolkur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMVorubolkur> SMVorubolkur1 { get; set; }
    }
}
