//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvgundantok
    {
        public int MvgUndantokId { get; set; }
        public Nullable<int> MvgTypaId { get; set; }
        public Nullable<int> DimensionirId { get; set; }
        public Nullable<int> NewMvgTypaId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Dimensionir Dimensionir { get; set; }
        public virtual MvgTypa MvgTypa { get; set; }
        public virtual MvgTypa MvgTypa1 { get; set; }
    }
}
