//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_bok_infoflow
    {
        public int rel_bok_infoflowId { get; set; }
        public int bokid { get; set; }
        public int postid { get; set; }
        public string documentvoucherno { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Bokingar Bokingar { get; set; }
    }
}
