//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_konto_felt
    {
        public int rel_konto_feltId { get; set; }
        public string virdi { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> KontoFeltDefId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual kontofeltdef kontofeltdef { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
    }
}
