//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_konto_flokkar
    {
        public int rel_konto_flokkarId { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> KontoflokkurId { get; set; }
    
        public virtual kontoflokkur kontoflokkur { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
    }
}
