//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_kontogruppa
    {
        public int kg_id { get; set; }
        public Nullable<int> upp_id { get; set; }
        public Nullable<int> slag_id { get; set; }
        public Nullable<int> kgl_id { get; set; }
        public string kgl_navn { get; set; }
        public Nullable<decimal> sortflet { get; set; }
        public Nullable<int> ros_id { get; set; }
        public Nullable<int> grundtal { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> lyklatal { get; set; }
    
        public virtual rokn_grundtol rokn_grundtol { get; set; }
        public virtual rokn_lyklatol rokn_lyklatol { get; set; }
        public virtual rokn_slag rokn_slag { get; set; }
        public virtual rokn_uppseting rokn_uppseting { get; set; }
    }
}
