//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_dimAnrOr
    {
        public int rokn_dimAndOrId { get; set; }
        public int rokn_reportsLinesId { get; set; }
        public bool Dim12 { get; set; }
        public bool Dim23 { get; set; }
        public bool Dim34 { get; set; }
        public bool Dim45 { get; set; }
        public byte[] rv { get; set; }
        public int Dim1Option { get; set; }
        public int Dim2Option { get; set; }
        public int Dim3Option { get; set; }
        public int Dim4Option { get; set; }
        public int Dim5Option { get; set; }
    
        public virtual rokn_reportsLines rokn_reportsLines { get; set; }
    }
}
