//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_uppseting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rokn_uppseting()
        {
            this.rokn_kontogruppa = new HashSet<rokn_kontogruppa>();
            this.rokn_uppsetingprbrukara = new HashSet<rokn_uppsetingprbrukara>();
        }
    
        public int upp_id { get; set; }
        public string upp_navn { get; set; }
        public string freetexthead { get; set; }
        public string freetextlines { get; set; }
        public byte[] rv { get; set; }
        public string frontpageline1 { get; set; }
        public string frontpageline2 { get; set; }
        public string frontpageline3 { get; set; }
        public string frontpageline4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_kontogruppa> rokn_kontogruppa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_uppsetingprbrukara> rokn_uppsetingprbrukara { get; set; }
    }
}
