//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_lykla_tmp
    {
        public int lnr { get; set; }
        public string lnavn { get; set; }
        public Nullable<decimal> lradfylgja { get; set; }
        public Nullable<int> upp_id { get; set; }
        public Nullable<int> fnr { get; set; }
        public Nullable<decimal> fradfylgja { get; set; }
        public Nullable<int> slag { get; set; }
        public Nullable<int> kontogr { get; set; }
        public string tegn { get; set; }
        public Nullable<decimal> tal { get; set; }
        public Nullable<decimal> tal_samanlikna { get; set; }
        public Nullable<decimal> tal_budget { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> ranks { get; set; }
        public Nullable<int> rankm { get; set; }
        public byte[] rv { get; set; }
    }
}
