//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_reportsUsers
    {
        public int rokn_reportsUsers_Id { get; set; }
        public Nullable<int> UsersId { get; set; }
        public Nullable<int> rokn_reportsId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual rokn_reports rokn_reports { get; set; }
        public virtual users users { get; set; }
    }
}
