//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_kontogruppalinjir
    {
        public int kgl_id { get; set; }
        public int kontonummar { get; set; }
        public int id { get; set; }
        public int upp_id { get; set; }
        public string debit_kredit { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> KontolistiId { get; set; }
    
        public virtual Kontolisti Kontolisti { get; set; }
    }
}
