//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_roknskapartol
    {
        public System.DateTime dato { get; set; }
        public int konto { get; set; }
        public Nullable<int> skuffa { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> kredit { get; set; }
        public string tidarskeid { get; set; }
        public string dimnavn1 { get; set; }
        public string dimnavn2 { get; set; }
        public string dimnavn3 { get; set; }
        public string dimnavn4 { get; set; }
        public string dimnavn5 { get; set; }
        public int arsnr { get; set; }
        public bool nb { get; set; }
        public Nullable<decimal> debit_hagtol { get; set; }
        public Nullable<decimal> kredit_hagtol { get; set; }
        public Nullable<decimal> debit_valuta { get; set; }
        public Nullable<decimal> kredit_valuta { get; set; }
    }
}
