//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rokn_reports()
        {
            this.rokn_reportsLines = new HashSet<rokn_reportsLines>();
            this.rokn_reportsUsers = new HashSet<rokn_reportsUsers>();
        }
    
        public int rokn_reportsId { get; set; }
        public string navn { get; set; }
        public byte[] rv { get; set; }
        public string frontpageline1 { get; set; }
        public string frontpageline2 { get; set; }
        public string frontpageline3 { get; set; }
        public string frontpageline4 { get; set; }
        public string freetexthead { get; set; }
        public string freetextlines { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_reportsLines> rokn_reportsLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_reportsUsers> rokn_reportsUsers { get; set; }
    }
}
