//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rokn_columncombination
    {
        public int columncombinationId { get; set; }
        public Nullable<int> ros_id { get; set; }
        public Nullable<int> kg { get; set; }
        public Nullable<int> slag_id { get; set; }
        public Nullable<int> kgl { get; set; }
        public string kgl_navn { get; set; }
        public Nullable<decimal> sortflet { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public Nullable<int> kontonummar { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> C { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> E { get; set; }
        public Nullable<decimal> F { get; set; }
        public Nullable<decimal> G { get; set; }
        public Nullable<decimal> H { get; set; }
        public Nullable<decimal> I { get; set; }
        public Nullable<decimal> J { get; set; }
        public Nullable<decimal> K { get; set; }
        public Nullable<decimal> L { get; set; }
        public Nullable<decimal> M { get; set; }
        public Nullable<decimal> N { get; set; }
        public Nullable<decimal> O { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> R { get; set; }
        public Nullable<decimal> S { get; set; }
        public Nullable<decimal> T { get; set; }
        public Nullable<int> kontoSort { get; set; }
        public Nullable<int> userId { get; set; }
        public byte[] rv { get; set; }
        public Nullable<decimal> A_h { get; set; }
        public Nullable<decimal> B_h { get; set; }
        public Nullable<decimal> C_h { get; set; }
        public Nullable<decimal> D_h { get; set; }
        public Nullable<decimal> E_h { get; set; }
        public Nullable<decimal> F_h { get; set; }
        public Nullable<decimal> G_h { get; set; }
        public Nullable<decimal> H_h { get; set; }
        public Nullable<decimal> I_h { get; set; }
        public Nullable<decimal> J_h { get; set; }
        public Nullable<decimal> K_h { get; set; }
        public Nullable<decimal> L_h { get; set; }
        public Nullable<decimal> M_h { get; set; }
        public Nullable<decimal> N_h { get; set; }
        public Nullable<decimal> O_h { get; set; }
        public Nullable<decimal> P_h { get; set; }
        public Nullable<decimal> Q_h { get; set; }
        public Nullable<decimal> R_h { get; set; }
        public Nullable<decimal> S_h { get; set; }
        public Nullable<decimal> T_h { get; set; }
        public Nullable<decimal> A_v { get; set; }
        public Nullable<decimal> B_v { get; set; }
        public Nullable<decimal> C_v { get; set; }
        public Nullable<decimal> D_v { get; set; }
        public Nullable<decimal> E_v { get; set; }
        public Nullable<decimal> F_v { get; set; }
        public Nullable<decimal> G_v { get; set; }
        public Nullable<decimal> H_v { get; set; }
        public Nullable<decimal> I_v { get; set; }
        public Nullable<decimal> J_v { get; set; }
        public Nullable<decimal> K_v { get; set; }
        public Nullable<decimal> L_v { get; set; }
        public Nullable<decimal> M_v { get; set; }
        public Nullable<decimal> N_v { get; set; }
        public Nullable<decimal> O_v { get; set; }
        public Nullable<decimal> P_v { get; set; }
        public Nullable<decimal> Q_v { get; set; }
        public Nullable<decimal> R_v { get; set; }
        public Nullable<decimal> S_v { get; set; }
        public Nullable<decimal> T_v { get; set; }
    }
}
