//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ryk_aldur_ryk
    {
        public int ryk_aldur_rykId { get; set; }
        public int bokid { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> Ryk_aldur_tmpId { get; set; }
    
        public virtual Bokingar Bokingar { get; set; }
        public virtual Ryk_aldur_tmp Ryk_aldur_tmp { get; set; }
    }
}
