//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldolisti
    {
        public int SaldolistiId { get; set; }
        public decimal Saldo { get; set; }
        public decimal debitiar { get; set; }
        public decimal kreditiar { get; set; }
        public Nullable<decimal> v_saldo { get; set; }
        public Nullable<decimal> v_debitiar { get; set; }
        public Nullable<decimal> v_kreditiar { get; set; }
        public Nullable<decimal> h_saldo { get; set; }
        public Nullable<decimal> h_debitiar { get; set; }
        public Nullable<decimal> h_kreditiar { get; set; }
        public Nullable<int> ArId { get; set; }
        public Nullable<int> KontolistiId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual Ar Ar { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
    }
}
