//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class skuffur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skuffur()
        {
            this.Bokingar = new HashSet<Bokingar>();
            this.Bokingar1 = new HashSet<Bokingar>();
            this.BokUpp = new HashSet<BokUpp>();
            this.BokUpp1 = new HashSet<BokUpp>();
            this.BokUpp2 = new HashSet<BokUpp>();
            this.BokUpp3 = new HashSet<BokUpp>();
            this.heimabankidef = new HashSet<heimabankidef>();
            this.skuffukonto = new HashSet<skuffukonto>();
            this.skuffurusers = new HashSet<skuffurusers>();
            this.tekstbokdef = new HashSet<tekstbokdef>();
        }
    
        public int SkuffurId { get; set; }
        public int sku_nummar { get; set; }
        public string sku_navn { get; set; }
        public bool bankaskuffa { get; set; }
        public string filnavn { get; set; }
        public string tekstslag { get; set; }
        public string flyttekstur { get; set; }
        public Nullable<int> ikkikrympa { get; set; }
        public Nullable<int> KreditKontolistiId { get; set; }
        public Nullable<int> TidarskeidId { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokingar> Bokingar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokingar> Bokingar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokUpp> BokUpp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokUpp> BokUpp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokUpp> BokUpp2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BokUpp> BokUpp3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<heimabankidef> heimabankidef { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skuffukonto> skuffukonto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skuffurusers> skuffurusers { get; set; }
        public virtual Tidarskeid Tidarskeid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tekstbokdef> tekstbokdef { get; set; }
    }
}
