//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMAvgreidslulinjur
    {
        public int Id { get; set; }
        public int AvgreidsluId { get; set; }
        public int LinjuNummar { get; set; }
        public Nullable<int> LinjuSlag { get; set; }
        public Nullable<int> VoruId { get; set; }
        public string VoruNummar { get; set; }
        public string Tekstur { get; set; }
        public string Tekstur2 { get; set; }
        public string VoruEind { get; set; }
        public Nullable<int> VoruEindId { get; set; }
        public Nullable<decimal> Nogd { get; set; }
        public Nullable<decimal> Aprisur { get; set; }
        public Nullable<decimal> Avslattur { get; set; }
        public Nullable<decimal> Upphadd { get; set; }
        public Nullable<decimal> MVGKr { get; set; }
        public Nullable<int> GjaldsHatturId { get; set; }
        public Nullable<int> SedlaHovdId { get; set; }
        public Nullable<int> KundaId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual SMAvgreidsluhovd SMAvgreidsluhovd { get; set; }
        public virtual SMGjaldshattur SMGjaldshattur { get; set; }
        public virtual SMVorur SMVorur { get; set; }
    }
}
