//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMBotntekstir
    {
        public int BotntekstirId { get; set; }
        public string Navn { get; set; }
        public int Sedlaslag { get; set; }
        public string Tekstur { get; set; }
        public byte[] rv { get; set; }
    }
}
