//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMGjaldshattur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMGjaldshattur()
        {
            this.SMAvgreidslulinjur = new HashSet<SMAvgreidslulinjur>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public Nullable<bool> ErVirkid { get; set; }
        public string Lysing { get; set; }
        public string Linjutekstur { get; set; }
        public Nullable<int> GjaldsSlag { get; set; }
        public Nullable<bool> OpnaSkuffu { get; set; }
        public Nullable<int> AvrundingOyru { get; set; }
        public byte[] rv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMAvgreidslulinjur> SMAvgreidslulinjur { get; set; }
    }
}
