//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMKassi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMKassi()
        {
            this.SMAvgreidsluhovd = new HashSet<SMAvgreidsluhovd>();
            this.SMKassauppteljing = new HashSet<SMKassauppteljing>();
        }
    
        public int Id { get; set; }
        public int Nummar { get; set; }
        public string Navn { get; set; }
        public Nullable<bool> HevurBonprintara { get; set; }
        public string BonprintaraPortur { get; set; }
        public Nullable<bool> HevurSkuffu { get; set; }
        public Nullable<bool> ErVirkin { get; set; }
        public int NastaBonId { get; set; }
        public int NastaUppteljingNr { get; set; }
        public Nullable<bool> VisVorunummar { get; set; }
        public Nullable<bool> VisEind { get; set; }
        public Nullable<bool> VisApris { get; set; }
        public Nullable<bool> VisNogd { get; set; }
        public Nullable<bool> VisLogo { get; set; }
        public string LogoFilnavn { get; set; }
        public Nullable<bool> BrukaTouchSkerm { get; set; }
        public string Gjaldoyru { get; set; }
        public string Firmanavn1 { get; set; }
        public string Firmanavn2 { get; set; }
        public string Firmanavn3 { get; set; }
        public string Firmanavn4 { get; set; }
        public string Firmanavn5 { get; set; }
        public string Firmanavn6 { get; set; }
        public string Email { get; set; }
        public string Heimasida { get; set; }
        public string Linjutekst1 { get; set; }
        public string Linjutekst2 { get; set; }
        public string Linjutekst3 { get; set; }
        public string Linjutekst4 { get; set; }
        public string Linjutekst5 { get; set; }
        public string Linjutekst6 { get; set; }
        public string Linjutekst7 { get; set; }
        public Nullable<int> KontaKassi { get; set; }
        public Nullable<int> KontaKassamunur { get; set; }
        public Nullable<int> KontaKassiStatus { get; set; }
        public Nullable<int> KontaBanki { get; set; }
        public Nullable<int> KontaTerminalkort { get; set; }
        public Nullable<int> SkuffaInngjold { get; set; }
        public Nullable<int> Dim1 { get; set; }
        public Nullable<int> Dim2 { get; set; }
        public Nullable<int> Dim3 { get; set; }
        public Nullable<int> Dim4 { get; set; }
        public Nullable<int> Dim5 { get; set; }
        public Nullable<int> KontaGavukort { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> KontuflokkurUtgjald { get; set; }
        public Nullable<bool> PrintAvgreidsluBon { get; set; }
        public Nullable<int> KontaOyramunur { get; set; }
        public Nullable<int> KontaDankort { get; set; }
    
        public virtual Dimensionir Dimensionir { get; set; }
        public virtual Dimensionir Dimensionir1 { get; set; }
        public virtual Dimensionir Dimensionir2 { get; set; }
        public virtual Dimensionir Dimensionir3 { get; set; }
        public virtual Dimensionir Dimensionir4 { get; set; }
        public virtual kontoflokkur kontoflokkur { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual Kontolisti Kontolisti1 { get; set; }
        public virtual Kontolisti Kontolisti2 { get; set; }
        public virtual Kontolisti Kontolisti3 { get; set; }
        public virtual Kontolisti Kontolisti4 { get; set; }
        public virtual Kontolisti Kontolisti5 { get; set; }
        public virtual Kontolisti Kontolisti6 { get; set; }
        public virtual Kontolisti Kontolisti7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMAvgreidsluhovd> SMAvgreidsluhovd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMKassauppteljing> SMKassauppteljing { get; set; }
    }
}
