//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSedlalinjur
    {
        public int SedlalinjurId { get; set; }
        public int SedlahovdId { get; set; }
        public int LinjuNummar { get; set; }
        public int Linjuslag { get; set; }
        public Nullable<int> VoruNummar { get; set; }
        public string Navn { get; set; }
        public Nullable<decimal> Nogd { get; set; }
        public Nullable<decimal> Eindarprisur { get; set; }
        public Nullable<decimal> AvslatturPct { get; set; }
        public Nullable<System.DateTime> Dagfesting { get; set; }
        public Nullable<System.DateTime> FysiskDagfesting { get; set; }
        public Nullable<System.DateTime> OkonomiskDagfesting { get; set; }
        public Nullable<decimal> Kostprisur { get; set; }
        public Nullable<decimal> Linjuprisur { get; set; }
        public Nullable<decimal> MVGKr { get; set; }
        public string Tekstur { get; set; }
        public byte[] rv { get; set; }
        public Nullable<int> VoruEind { get; set; }
        public Nullable<int> Dim1 { get; set; }
        public Nullable<int> Dim2 { get; set; }
        public Nullable<int> Dim3 { get; set; }
        public Nullable<int> Dim4 { get; set; }
        public Nullable<int> Dim5 { get; set; }
    
        public virtual Dimensionir Dimensionir { get; set; }
        public virtual Dimensionir Dimensionir1 { get; set; }
        public virtual Dimensionir Dimensionir2 { get; set; }
        public virtual Dimensionir Dimensionir3 { get; set; }
        public virtual Dimensionir Dimensionir4 { get; set; }
        public virtual eindir eindir { get; set; }
        public virtual SMSedlahovd SMSedlahovd { get; set; }
        public virtual SMVorur SMVorur { get; set; }
    }
}
