//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSedlahovd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMSedlahovd()
        {
            this.SMSedlalinjur = new HashSet<SMSedlalinjur>();
        }
    
        public int SedlahovdId { get; set; }
        public int Sedlaslag { get; set; }
        public int Sedlastatus { get; set; }
        public long Sedlanr { get; set; }
        public Nullable<long> RefGoymslusedilnr { get; set; }
        public Nullable<long> RefTilbodsnr { get; set; }
        public Nullable<long> RefOrdraNummar { get; set; }
        public Nullable<long> RefSakNummar { get; set; }
        public Nullable<long> RefFakturaNummar { get; set; }
        public int Kontonr { get; set; }
        public string Navn { get; set; }
        public string Adressa1 { get; set; }
        public string Adressa2 { get; set; }
        public string Adressa3 { get; set; }
        public string Adressa4 { get; set; }
        public string Attention { get; set; }
        public int LeveringKontoNummar { get; set; }
        public Nullable<int> Gjaldstreyt { get; set; }
        public string UmbididAv { get; set; }
        public string Solufolk { get; set; }
        public string RekvisitionsNummar { get; set; }
        public Nullable<System.DateTime> Sedladagur { get; set; }
        public Nullable<System.DateTime> Fakturadagur { get; set; }
        public Nullable<System.DateTime> Bokingardagur { get; set; }
        public Nullable<System.DateTime> Leveringsdagur { get; set; }
        public string Tekstur1 { get; set; }
        public string Tekstur2 { get; set; }
        public Nullable<System.DateTime> FakturaUtskrivaDagur { get; set; }
        public Nullable<System.DateTime> FakturaTeldupostDagur { get; set; }
        public string GodkentAv { get; set; }
        public byte[] rv { get; set; }
        public Nullable<System.DateTime> FakturaOioxmlDagur { get; set; }
    
        public virtual Kontolisti Kontolisti { get; set; }
        public virtual Kontolisti Kontolisti1 { get; set; }
        public virtual SMGjaldstreyt SMGjaldstreyt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur { get; set; }
    }
}
