//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMVorur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMVorur()
        {
            this.SMAvgreidslulinjur = new HashSet<SMAvgreidslulinjur>();
            this.SMSedlalinjur = new HashSet<SMSedlalinjur>();
        }
    
        public int VorurId { get; set; }
        public string VoruNummar { get; set; }
        public string Navn { get; set; }
        public string Strikukota { get; set; }
        public Nullable<decimal> Keypspris { get; set; }
        public Nullable<decimal> KostPct { get; set; }
        public Nullable<decimal> Kostpris { get; set; }
        public Nullable<decimal> VinningPct { get; set; }
        public Nullable<decimal> Solupris { get; set; }
        public Nullable<decimal> SoluprisVMVG { get; set; }
        public Nullable<int> VeitaraNummar { get; set; }
        public string VeitaraVoruNummar { get; set; }
        public int Vorubolkur { get; set; }
        public int Voruslag { get; set; }
        public int Eind { get; set; }
        public bool Mvgskyldug { get; set; }
        public bool Virkin { get; set; }
        public byte[] rv { get; set; }
        public string Lokation { get; set; }
        public string Navn2 { get; set; }
    
        public virtual eindir eindir { get; set; }
        public virtual Kontolisti Kontolisti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMAvgreidslulinjur> SMAvgreidslulinjur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSedlalinjur> SMSedlalinjur { get; set; }
        public virtual SMVorubolkur SMVorubolkur { get; set; }
    }
}
