//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlversion
    {
        public int SqlVersionId { get; set; }
        public int sqlversion1 { get; set; }
        public System.DateTime datoklokka { get; set; }
        public byte[] rv { get; set; }
    }
}
