//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tekstbokdef
    {
        public int TekstBokDefId { get; set; }
        public string navn { get; set; }
        public string bokslag { get; set; }
        public string teknsett { get; set; }
        public string pathtekstbokingar { get; set; }
        public string fileextension { get; set; }
        public string pathkopi { get; set; }
        public string serformat_navn { get; set; }
        public string pathextcall { get; set; }
        public bool waitafterextcall { get; set; }
        public Nullable<int> SkuffurId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual skuffur skuffur { get; set; }
    }
}
