//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.Bokingar = new HashSet<Bokingar>();
            this.emaillog = new HashSet<emaillog>();
            this.hopflyting = new HashSet<hopflyting>();
            this.Kontolisti = new HashSet<Kontolisti>();
            this.KontoVidmerking = new HashSet<KontoVidmerking>();
            this.rokn_reportsUsers = new HashSet<rokn_reportsUsers>();
            this.rokn_uppsetingprbrukara = new HashSet<rokn_uppsetingprbrukara>();
            this.skuffurusers = new HashSet<skuffurusers>();
        }
    
        public int UsersId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public Nullable<int> SkuffurId { get; set; }
        public Nullable<int> TidarskeidId { get; set; }
        public byte[] rv { get; set; }
        public int AuthenticationLevel { get; set; }
        public Nullable<int> KsKota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokingar> Bokingar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emaillog> emaillog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hopflyting> hopflyting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontolisti> Kontolisti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KontoVidmerking> KontoVidmerking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_reportsUsers> rokn_reportsUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rokn_uppsetingprbrukara> rokn_uppsetingprbrukara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skuffurusers> skuffurusers { get; set; }
        public virtual Tidarskeid Tidarskeid { get; set; }
    }
}
