//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_variablar
    {
        public int web_variablarId { get; set; }
        public string var_navn { get; set; }
        public string virdi { get; set; }
        public Nullable<int> IUsersId { get; set; }
        public byte[] rv { get; set; }
    
        public virtual iusers iusers { get; set; }
    }
}
