using BootstrapWebApplication.Controllers;
using BootstrapWebApplication.DAL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeTester
{
    public class DatabaseConvert
    {
        JsonSerializer serializer = new JsonSerializer();

        public DatabaseConvert() {}

        public void Convert<T>(string file, Action<object> convertAction)
        {
            var json = Deserialize<T>(file);
            json.ForEach(i => { convertAction(i); });
        }

        private List<T> Deserialize<T>(string file)
        {
            var cc = new CountryController();
            JsonTextReader reader = new JsonTextReader(new StreamReader(file));
            return serializer.Deserialize<List<T>>(reader);
            //JsonSerializer se = new JsonSerializer();
            //StreamReader re = new StreamReader(file);
            //JsonTextReader reader = new JsonTextReader(re);
            //return se.Deserialize(reader);
        }
    }
}
/**

ADRESS (Adress): ID,NR,FNAVN,ENAVN,ADR1,ADR2,RET_DATO,RET_HH,RET_MM,RET_ID

ARBTYPER (Arbei's-sl|g/b`tispartar): ID,ARB_TYPE,ARB_TEKST,PCT_ANDEL,KR_TILLAG,RET_DATO,RET_HH,RET_MM,RET_ID

AR_LOG (Ar_log): ID,NR,AR

DEB_CON (Deb_con): ID,NR,NR_DEB,SALDO,RET_DATO,RET_HH,RET_MM,RET_ID

DUMMY (Dummy): ID,NR,TXT,TXT2,OK

F100 (F100): ID,NR,FODT,FNAVN,ENAVN,ADR1,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID,FN5,STRIKA,KYN,EN5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,KOTA,ENFO,CPR,MNAVN,UPPHADD,OPRET,OPDAT,OLD_NR,ARSTAL,NY_F_DATO,FUNDET,PRI,STATUS,ARB_NR,REG_NR,KONTO,REG_NR_FF,KONTO_FF,FLYT_DATO,KOYR_DATO,ART

FAXNR (Faxnr): ID,FAX_NR,DEILD,RET_DATO,RET_HH,RET_MM,RET_ID

FF_GR (Ff_gr): ID,FFNR,GRNR,RET_DATO

FIRMA (Firma): ID,NAVN,ADR1,ADR2,ADR3,ORDNR,PERS_NR,SKJAL_NR,RET_DATO,RET_HH,RET_MM,RET_ID,RENS_OK,AVIS_NR,FF,FORELDNR,FRI_MIN,UDSKR_NR,CHK_KALL,KOYR_NR,UD_OK,NAT_ADD,BARN,LARARANR,GREIN_NR,OP_SYS,STROKE_TIME,JOB_NR,OPR_LOG,MI_NR,LG_NR,VIS_BETALER,S_SEKUND,TR_NR,TRP_NR,FRT_NR,A_TAL_LG,LJG_VID,FRT_TOT_NR,LO_NR,F_REG,F_KTO,F_PCT,DIRT,DIRT2

FISKART (Fiskart): ID,ID,NAVN,STUTT,ALIAS,RET_DATO,RET_HH,RET_MM,RET_ID,LINK,RAD

FISKKODE (Fiskasl|g): ID,FISK_ART,FISK_TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

FISKPRIS (Fiskpris): ID,ART,FRA_DATO,TIL_DATO,PRIS,RET_DATO,RET_HH,RET_MM,RET_ID

FLEXERRS (@dataflex error file): ID,ERROR_DESCR,NOTE

FRAD_ART (Frad_art): ID,ID,NAVN,STUTT,ALIAS,RET_DATO,RET_HH,RET_MM,RET_ID,LINK,RAD,TYPA

FRM_LINK (Frm_link): ID,FRT_NR,TR_NR,PERS_NR,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,SKIB_ID,TUR_ID,FRT_TOT_NR

FRT_HOVD (Frt_hovd): ID,ARB_NR,FLYT_DATO,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,UPPH_ELE,RET_DATO,RET_HH,RET_MM,RET_ID,PERS_NR,ART,KOYR_DATO,FRT_NR,KONTO,REG_NR,KONTO_FF,REG_NR_FF,FRT_TOT_NR,PLUS,TR_NR,X

FRT_LINK (Frt_link): ID,FRT_NR,TR_NR,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,SKIB_ID,TUR_ID,FRT_TOT_NR

FRT_LON (Frt_lon): ID,NR,AR,FRTLON,TRSP,FRT_DATO,TRS_DATO,LO_KR_A,LO_KR_F,LO_KR_FRT,LO_DATO,DG_AR,TU_AR,DATO_AR,ID_AR,SAML_KR,SAML_KR2

FRT_TOT (Frt_tot): ID,ARB_NR,FLYT_DATO,UPPH_KR,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,UPPH_ELE,RET_DATO,RET_HH,RET_MM,RET_ID,IN_LN,KOYR_DATO,ART,KOYR_DIV,FRT_TOT_NR

FR_LINE (Fr_line): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS

FR_TMP (Fr_tmp): ID,NR,KR92_0,KR93_0,KR93_1,KR92_1

G100 (G100): ID,NR,FODT,FNAVN,ENAVN,ADR1,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID,FN5,STRIKA,KYN,PRI_OWN,BETALER,EN5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,M_STATUS,TXT_LN,TLF_HEIMA,TYPE,ENFO,CPR,STARV,BURT_DG,TUR_IALT,INN_IALT,DG,MD,STAT,TXT_DATO,LAST_DATO,MNAVN,MI_TOT,LG_TOT,MI_AR,MI_ID,LG_AR,LG_KR,LAST_ID,ETI_DATO,ETI_HH,ETI_MM,ETI_ID,SLAG,TRANSPORT,LG_IALT,LAST_KONTO,LAST_REG

HOVD (Hovd): ID,SKIP,FRA_DATO,TIL_DATO,SKJAL_NR,PAR_SKIP,PAR_SKJAL,MANTAL,PRIS_DATO,STUD_DATO,AVR_STAD,SKIP_ART,IND_DATO,IND_HH,IND_MM,IND_ID,STATUS,UDSKREVET,UPPTALD,UD_DATO,UD_HH,UD_MM,UD_ID,KG_IALT,UPPH_IALT,TIL_SKIP_PCT,TIL_SKIP_KR,TIL_MANN_PCT,TIL_MANN_KR,LOBNR,VIDAR,RET_DATO,RET_HH,RET_MM,RET_ID,LN_IALT

INFOSYS (Uppl`sningar um virki'): ID,NAVN,ADR_1,ADR_2,POSTNR,TLF,KONTO_1,KONTO_2,GIRO_1,DAGSDATO,RET_DATO,RET_HH,RET_MM,RET_ID

KONTTXT (Konttxt): ID,NR,NAVN,ANTAL,RET_DATO,RET_HH,RET_MM,RET_ID,NAVNKEY

K_DATO (K_dato): ID,KOYR_DATO,RET_DATO,RET_HH,RET_MM,RET_ID

LEV (Leverand›r): ID,LEVNR,LEVNAVN,ADR1,ADR2,POSTNR,TELEFON,TELEFAX,KONTAKT,KONTAKT2,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,NATJOB,LN_IALT

LGJALD (Lgjald): ID,LG_NR,NR,AR,STARV,PRIS,ING_DATO,ING_NR,RET_DATO,RET_HH,RET_MM,RET_ID,ING_HH,ING_MM,ING_ID,SJ_NR,ANT_LN_TXT,REG_NR,KONTO,FRT_LON,LGJ,KOTA,TRANSP_IALT,SLAG,K1,UDS

LGJALD2 (Lgjald2): ID,LG_NR,NR,U1,U2,U3,U4,U5,U6,U7

LG_TXT (Lg_txt): ID,LG_NR,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

LIMAGJ (Skr#setingar av limagjaldi): ID,LIMART,ME_NUMMER,ARSTAL,BELOB,ING_DATO,RET_DATO,RET_HH,RET_MM,RET_ID

LIMART (Limatypir): ID,LIMART,TXT,MEDL_IALT,MEDL_HAN,MEDL_HUN,OPTALT,RET_DATO,RET_HH,RET_MM,RET_ID

LINE (Line): ID,SKJAL_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID

LOYVIR (Loyvir): ID,PROG_ID,PER_ID,RUN_OK,LES_OK,SKRIV_OK,DEL_OK,KEY,DAG_STAT,FRA_HH,FRA_MM,TIL_HH,TIL_MM,FRA_HH1,FRA_MM1,TIL_HH1,TIL_MM1,LOG,STROKE_TIME,STROKE_CHK

LO_HOVD (Lo_hovd): ID,LO_NR,ARB_NR,SKIB_ID,FRA_DATO,TIL_DATO,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,ANT_LN_TXT,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,KR_IALT_A,KR_IALT_F,KR_IALT_FRT,SK_A,KO_A,SK_FR,KO_FR,MANS_IALT,SKEI,UT_DATO,UT_HH,UT_MM,UT_ID,UT_ANT

LO_LINE (Lo_line): ID,LO_NR,PERS_NR,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,ANT_LN_TXT,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,KR_A,KR_F,SK_P,KO_P,KR_FRT,SK_F,KO_F,FODT,CPR,ARB_NR

LSLAG (Lslag): ID,ID,TEKSTUR,STUTT,RET_DATO,RET_HH,RET_MM,RET_ID,BREV_UT,FLYTAST,DLISTA,BLISTA,ARS_LISTI

MANGLA (Mangla): ID,MI_NR,ID,FRA,TIL

MANNING (Limir/manningar): ID,LIMART,ME_NUMMER,FODT,TLF,FOEN,FNAVN,MNAVN,ENAVN,ADR_1,ADR_2,POSTNR,POSTBOX,KON,BE_ME_NUMMER,M_TYPE,SALDO,ARB_TYPE,CPR,PCT_PART,RET_DATO,RET_HH,RET_MM,RET_ID

MA_LINE (Ma_line): ID,TR_NR,PERS_NR,PARTAR,KR,TILLAG1,TILLAG2,FRADRATT1,KR_IALT,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,FRA_DATO,SKIB_ID

MDAGAR (Mdagar): ID,AR,TYPA,DAGAR,MANS,IALT

MI2_HOVD (Mi2_hovd): ID,MI_NR,PERS_NR,SKIB_ID,AR,FRA_DATO,TIL_DATO,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,ANT_LN_TXT,SK_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,PART,KR_IALT,KG_IALT,ID_TUR,STARV,TR_NR,FRT_PART,TIL_PR_DG,TIL_PR_TUR,PART_NETTO,FODT,ARB_NR,I_PART,FRT_NR,JN,TRYG_JN,TRYG_KR,TRYG_KVT,STARV20

MINLON (Minlon): ID,FRA_DATO,TIL_DATO,PR_MD,PR_DG,RET_DATO,RET_HH,RET_MM,RET_ID,KOTA

MI_HNOT (Mi_hnot): ID,MI_NR,PAGE,LAST_USED_LIN,L01,L02,L03,L04,L05,L06,L07,L08,L09,L10,L11,L12

MI_HOVD (Mi_hovd): ID,MI_NR,PERS_NR,SKIB_ID,AR,FRA_DATO,TIL_DATO,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,ANT_LN_TXT,SK_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,PART,KR_IALT,KG_IALT,ID_TUR,STARV,TR_NR,FRT_PART,TIL_PR_DG,TIL_PR_TUR,PART_NETTO,FODT,ARB_NR,I_PART,FRT_NR,JN,TRYG_JN,TRYG_KR,TRYG_KVT

MI_TMP (Mi_tmp): ID,PERS_NR,FRA_DATO,AR,STARV,ANT

MI_TXT (Mi_txt): ID,MI_NR,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

MUNUR (Munur): ID,NR,KR_OK,KR_NOT_OK

NOTEPAD (@notepad dummy file): ID,LINE,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,F11,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34,F35,F36,F37,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47,F48,F49,F50,F51,F52,F53,F54,F55,F56,F57,F58,F59,F60,F61,F62,F63,F64,F65,F66,F67,F68,F69,F70,F71,F72,F73,F74,F75,F76,F77,F78,F79,F80,F81,ASCII_SET,KEYTXT01,KEYTXT02,KEYTXT03,KEYTXT04,KEYTXT05,KEYTXT06,KEYTXT07,KEYTXT08,KEYTXT09,KEYTXT10,KEYTXT11,KEYTXT12,KEYTXT13,KEYTXT14,KEYTXT15,KEYTXT16,KEYTXT17,KEYTXT18,KEYTXT19,KEYTXT20,KEYTXT21,KEYTXT22,KEYTXT23,KEYTXT24,KEYTXT25,KEYTXT26,KEYTXT27,KEYTXT28,KEYTXT29,KEYTXT30,KEYTXT31,KEYTXT32,KEYTXT33,KEYTXT34,KEYTXT35,KEYTXT36,KEYTXT37,KEYTXT38,KEYTXT39,KEYTXT40,KEY01,KEY02,KEY03,KEY04,KEY05,KEY06,KEY07,KEY08,KEY09,KEY10,KEY11,KEY12,KEY13,KEY14,KEY15,KEY16,KEY17,KEY18,KEY19,KEY20,KEY21,KEY22,KEY23,KEY24,KEY25,KEY26,KEY27,KEY28,KEY29,KEY30,KEY31,KEY32,KEY33,KEY34,KEY35,KEY36,KEY37,KEY38,KEY39,KEY40,YES,NO,INSERT,OVERWRITE,WAIT,MSG01,MSG02,MSG03,MSG04,MSG05,MSG06,MSG07,MSG08,MSG09,MSG10,MSG11,MSG12,MSG13,MSG14,MSG15,MSG16,MSG17,MSG18,MSG19,MSG20,COLOR1,COLOR2,COLOR3,COLOR4,COLOR5

P100 (P100 limir): ID,NR,FODT,FNAVN,ENAVN,ADR1,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID,FN5,STRIKA,KYN,PRI_OWN,BETALER,EN5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,M_STATUS,TXT_LN,TLF_HEIMA,TYPE,ENFO,CPR,STARV,BURT_DG,TUR_IALT,INN_IALT,DG,MD,STAT,TXT_DATO,LAST_DATO,MNAVN,MI_TOT,LG_TOT,MI_AR,MI_ID,LG_AR,LG_KR,LAST_ID,ETI_DATO,ETI_HH,ETI_MM,ETI_ID,SLAG,TRANSPORT,LG_IALT,LAST_KONTO,LAST_REG,FKOTA

P1_NOT (P1_not): ID,NR,PAGE,LAST_USED_LIN,L01,L02,L03,L04,L05,L06,L07,L08,L09,L10,L11,L12

P200 (P200 skip): ID,ID,NAVN,ADR1,POSTNR,TLF,FAX,KONTAKT,KONTAKT2,IND_REG,UD_REG,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,LN_IALT,SK_TYPA,REDERI,TONNAGE,HK,TXT_LN,TXT_DATO,BURT_DG,TUR_IALT,LAST_DATO,TYPA,STRIKA,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STAT,AV_IALT,KG_IALT,DG_IALT,ALT_ID,GRUPPE,ETI_DATO,ETI_HH,ETI_MM,ETI_ID,ARB_NR

P2000 (P2000): ID,ID,ID_FF,NAVN,ID_GR,RET_DATO

P300 (P300 reiÐar¡): ID,ID,NAVN,ADR1,ADR2,POSTNR,TLF,FAX,KONTAKT,KONTAKT2,IND_REG,UD_REG,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,LN_IALT,TXT_LN,TXT_DATO,AVR_IALT,KG_IALT,LAST_DATO,LAST_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STUTT,MODEM,DISK_DATO,DISK_NU,DISK_IALT,PREFIX,SKIB_IALT,ALT_ID,ETI_DATO,ETI_HH,ETI_MM,ETI_ID,STAT,ARB_NR,FRT_LON,FRT_LON_DATO,FRT_LON_NU,A_REG,A_KTO

P400 (P400): ID,NR,FNAVN,ENAVN,POST,KR,ART,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,UD_DATO,UD_HH,UD_MM,UD_ID,REG,KONTO

P600 (P600): ID,ID,NAVN,ADR1,ADR2,POSTNR,TLF,FAX,KONTAKT,KONTAKT2,IND_REG,UD_REG,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,LN_IALT,TXT_LN,TXT_DATO,AVR_IALT,KG_IALT,LAST_DATO,LAST_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STUTT,MODEM,DISK_DATO,DISK_NU,DISK_IALT

PASSORD (Passord): ID,PASSORD,ID,PR_NAME,PAGEEND,FORMFEED,L_PR_NAME,L_FORMFEED,L_PAGEEND,L_PNR,F_PNR,AKTIV,LOGIN_DATO,LOGIN_HH,LOGIN_MM,RET_DATO,RET_HH,RET_MM,RET_ID,PRI_OWN,PRI_GRP,CONV,CHK_KAL,LOYNA1,LOYND2,RENS_OK,TRIAL,LOYNA2,TYPA,PR_DEV,LPR_DEV,LOG,LOGOUT_DATO,LOGOUT_HH,LOGOUT_MM,SESSION_NOW_MM,SESSION_TOT_MM

PCTST (Pctst): ID,NR,TXT1,TXT2,RET_DATO,RET_HH,RET_MM,RET_ID,T5,STATUS

POSTNR (Uppl`sningar um bygd/postnummar): ID,POSTNR,BYGD,MEDL_IALT,MEDL_HAN,MEDL_HUN,RET_DATO,RET_HH,RET_MM,RET_ID,RET_ID

PTXT (Ptxt): ID,NR,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

REDERI (Rederi): ID,NR,NAVN,ADR1,ADR2,POSTNR,TELEFON,TELEFAX,KONTAKT,KONTAKT2,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,LN_IALT

REG_NR (Reg_nr): ID,REG_NR,REG_NAVN,RET_DATO,RET_HH,RET_MM,RET_ID

REIDARI (Upplysningar um rei'ar$): ID,RE_NUMMER,TLF,FOEN,FNAVN,ENAVN,ADR_1,ADR_2,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID

REMINDER (Reminder): ID,DATO,NR,JN,ANT,UTDATO,ER_P,AVM_DATO,AVM_ID,DAGAR,BRV_OK,KOTA

S100 (S100): ID,NR,FODT,FNAVN,ENAVN,ADR1,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID,FN5,STRIKA,KYN,EN5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,KOTA,ENFO,CPR,MNAVN,REG_NR,KONTO,FRT_LON,LGJ,ING,OPRET,OPDAT,OLD_NR,ARSTAL,NY_F_DATO,FUNDET,PRI

SADRESS (Sadress): ID,NR,FNAVN,ENAVN,ADR1,ADR2,RET_DATO,RET_HH,RET_MM,RET_ID

SB (Sb): ID,NR,FODT,FNAVN,ENAVN,ADR1,POSTNR,RET_DATO,RET_HH,RET_MM,RET_ID,FN5,STRIKA,KYN,PRI_OWN,BETALER,EN5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,M_STATUS,TXT_LN,TLF_HEIMA,TYPE,ENFO,CPR,STARV,BURT_DG,TUR_IALT,INN_IALT,DG,MD,STAT,TXT_DATO,LAST_DATO,MNAVN,MI_TOT,LG_TOT,MI_AR,MI_ID,LG_AR,LG_KR,LAST_ID,ETI_DATO,ETI_HH,ETI_MM,ETI_ID,SLAG,LG_IALT,TRANSPORT

SHAG (Shag): ID,ID,AR,MD,FISK,KG,KR,TUR_IALT,DAG_IALT,RET_DATO,RET_HH,RET_MM,RET_ID

SKIB (Skib): ID,ID,NAVN,ADR1,ADR2,POSTNR,TELEFON,TELEFAX,KONTAKT,KONTAKT2,IND_REG,UD_REG,STATUS,RET_DATO,RET_HH,RET_MM,RET_ID,NAVN5,ILUL,LN_IALT,SK_TYPA,REDERI,TONNAGE,HK,TXT_LN_IALT

SKIBMAN (Skibman): ID,ME_NUMMER,ARSTAL,FRA_DATO,TIL_DATO,SKIBS_KODE,SKIBS_NAVN,RET_DATO,RET_HH,RET_MM,RET_ID

SKIP (Uppl`sningar um skip): ID,SK_NUMMER,FOEN,FNAVN,SK_TYPE,RE_NUMMER,TONNAGE,HK,IND_REG,UD_REG,RET_DATO,RET_HH,RET_MM,RET_ID

SKIPMAN (Skipman): ID,PERS_NR,FRA_DATO,TIL_DATO,SKIP_ID,STARV,PCT_PART,TILLAG,RET_DATO,RET_HH,RET_MM,RET_ID

SKIPTYPA (Skiptypa): ID,ART,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

SKIPTYPE (Skipasl|g): ID,SK_TYPE,SK_TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

SKOTA (Skota): ID,PERS_NR,AR,STARV,LOBNR,ANT

STARV (Starv): ID,ID,TEKSTUR,RET_DATO,RET_HH,RET_MM,RET_ID,TEKSTUR2,STUTT,TXT5,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,ANTAL,TAL_DATO,TAL_HH,TAL_MM,TAL_ID,PART,TIL_DG,TIL_TUR,FELAG

STAT (Stat): ID,ID,TEKSTUR,STUTT,RET_DATO,RET_HH,RET_MM,RET_ID,BREV_UT,FLYTAST,DLISTA,BLISTA,ARS_LISTI

STUDART (Studart): ID,ID,NAVN,STUTT,ALIAS,RET_DATO,RET_HH,RET_MM,RET_ID,LINK,RAD,TYPA

STUDDATO (Studnings-dato): ID,STUD_DATO,STUD_KODE,STUD_PRIS,RET_DATO,RET_HH,RET_MM,RET_ID,RET_ID

STUDPRIS (Studpris): ID,ART,FRA_DATO,TIL_DATO,PRIS,RET_DATO,RET_HH,RET_MM,RET_ID,KOTA,SKIP,FID

STUDTYPE (Studnings-typir): ID,STUD_KODE,STUD_TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

STXFI (Stxfi): ID,ST_ID,FI_ID,RET_DATO,RET_HH,RET_MM,RET_ID

STXSK (Stxsk): ID,ST_ID,SK_ID,FRA_DATO,TIL_DATO,PCT_PART,TILLAG,LGJALD,RET_DATO,RET_HH,RET_MM,RET_ID

STXT (Stxt): ID,NR,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

TELUP (Telup): ID,NR,RET_DATO,RET_HH,RET_MM,RET_ID

TLF_IN (Tlf_in): ID,NR,DATO,HH,MM,ID

TLF_TMP (Tlf_tmp): ID,TR_NR,PERS_NR,SKIB_ID,FRA_DATO,MI_NR,INX,DAGE

TMP_522 (Tmp_522): ID,TR_NR

TMP_BYTI (Tmp_byti): ID,ID,RAD,F0,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13

TMP_UTS (Tmp_uts): ID,ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,UD_DATO,UD_HH,UD_MM,UD_ID,STAT

TRANSPRT (Transprt): ID,PERS_NR,TRP_NR,AR,RET_DATO,RET_HH,RET_MM,RET_ID,SJ_NR,ANT_LN_TXT,REG_NR,KONTO,UPPH_IALT,UTG_DATO,UD_DATO,UD_HH,UD_MM,UD_ID,UD_NR,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,HEINTA,FAX_NR,REG_FRA,KONTO_FRA,EN,FN

TRANS_LG (Trans_lg): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,LG_NR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_MI (Trans_mi): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,MI_NR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_P (Trans_p): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,PERSNR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_R (Trans_r): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,R_NR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_S (Trans_s): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,ID,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_TP (Trans_tp): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,TRP_NR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_TR (Trans_tr): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,TR_NR,STATUS,UDSKR_NR,FRA,TIL,FELT

TRANS_V (Trans_v): ID,IND_DATO,IND_HH,IND_MM,IND_ID,IND_TTY,PROG,ID,STATUS,UDSKR_NR,FRA,TIL,FELT

TR_HOVD (Tr_hovd): ID,ID_SKIB,ID_TUR,FRA_DATO,TIL_DATO,TR_NR,PAR_SKIP,PAR_SKJAL,MANNING,AVR_STAD,SK_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,UDSKREVET,UPPTALD,UD_DATO,UD_HH,UD_MM,UD_ID,KG_IALT,UPPH_IALT,TIL_SKIP_PCT,TIL_SKIP_KR,TIL_MANN_PCT,TIL_MANN_KR,LOBNR,VIDAR,RET_DATO,RET_HH,RET_MM,RET_ID,LN_IALT,ANT_LN_TXT,TUR_NR,AVR_DATO,DAGAR,ID_REDERI,MANNING_I,SKIP_STUD,MAN_STUD,TILSKOT,FRADRAG,TIL_MANN_TOT,FRADRAG2,MANN_PART,PR_DAG,MINLON,DAGLON,SKIB_TXT,TOTAL_KR,MANN_PART_IS,MID_AR,MANN_PART_I,ARB_NR,PAR_ART,PAR_TUR_ID,MANNING_X,ALT_MP,ALT_MA,CHECK,TRYG_ANT,TRYG_KR,TRYG_KRHB,TRYG_KVIT,TRYG_BILAG,TRYG_DATO

TR_KRED (Tr_kred): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,ALT_PRIS,KR,AVR_STAD,AVR_DATO

TR_LINE (Tr_line): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,ALT_PRIS,KR,AVR_STAD,AVR_DATO,RAD,AR,SK_ID,STUD_M,STUD_S

TR_STUD (Tr_stud): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,ALT_PRIS,KR,AVR_STAD,AVR_DATO

TR_STUDM (Tr_studm): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,ALT_PRIS,KR,AVR_STAD,AVR_DATO

TR_STUDS (Tr_studs): ID,TR_NR,ART,NOGD,PRIS,S_STUD_JN,M_STUD_JN,RET_DATO,RET_HH,RET_MM,RET_ID,OPR_DATO,OPR_HH,OPR_MM,OPR_ID,STATUS,ALT_PRIS,KR,AVR_STAD,AVR_DATO

TR_TXT (Tr_txt): ID,TR_NR,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

TURHEAD (Header fyri avrei'ing): ID,SK_NUMMER,TUR_START,TUR_SLUT,PAR_SK_NUMMER,MANTAL,PRIS_DATO,STUD_DATO,AVR_STED,SK_TYPE,INCL_AAR,RET_DATO,RET_HH,RET_MM,RET_ID

TYPA (Typa): ID,ID,TEKSTUR,STUTT,RET_DATO,RET_HH,RET_MM,RET_ID,BREV_UT,FLYTAST,DLISTA,BLISTA,ARS_LISTI

UM_LINE (Um_line): ID,NR,FRA_DATO,TIL_DATO,DG,ALM_UPPH,PR_DG,FF_IALT,AR,RET_DATO,RET_HH,RET_MM,RET_ID,UD_DATO,UD_HH,UD_MM,UD_ID,UD_ANT,REG,KONTO,OPR_DATO,OPR_HH,OPR_MM,OPR_ID

VARETXT (Varetxt): ID,VORUNR,LNR,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

VHAG (Vhag): ID,ID,AR,MD,FISK,KG,KR,TUR_IALT,DAG_IALT,RET_DATO,RET_HH,RET_MM,RET_ID

VIRKI (Virki): ID,ART,TEKST,ADR1,POSTNR,TELEFON,FAX,KONTAKT,RET_DATO,RET_HH,RET_MM,RET_ID

VTXT (Vtxt): ID,ID,LINJE,TEKST,RET_DATO,RET_HH,RET_MM,RET_ID

frt_lon7 (Frt_lon7): ID,NR,AR,FRTLON,TRSP,FRT_DATO,TRS_DATO,LO_KR_A,LO_KR_F,LO_KR_FRT,LO_DATO,DG_AR,TU_AR,DATO_AR,ID_AR,SAML_KR,SAML_KR2

tmp_byt2 (Tmp_byt2): ID,ID,RAD,F0,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,SKID,DATO1,DATO2,BROK,SKID2
*/
