//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEB_CON
    {
        public int DEB_CON_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public Nullable<int> NR_DEB { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }

        public string StarvId { get; set; }
        public int? PostNrPostnr { get; set; }
        public string LslagId { get; set; }


        //public virtual Member P100 { get; set; }
    }
}
