//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;

    //"ID";"ARB_NR";"FLYT_DATO";"OPR_DATO";"OPR_HH";"OPR_MM";"OPR_ID";"STATUS";"UPPH_ELE";"RET_DATO";"RET_HH";"RET_MM";"RET_ID";"PERS_NR";"ART";"KOYR_DATO";"FRT_NR";"KONTO";"REG_NR";"KONTO_FF";"REG_NR_FF";"FRT_TOT_NR";"PLUS";"TR_NR";"X"
    public partial class FRT_HOVD
    {
        public int Id { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public Nullable<System.DateTime> FLYT_DATO { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> UPPH_ELE { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public string ART { get; set; }
        public Nullable<System.DateTime> KOYR_DATO { get; set; }
        public Nullable<int> FRT_NR { get; set; }
        public Nullable<int> KONTO { get; set; }
        public Nullable<int> REG_NR { get; set; }
        public Nullable<int> KONTO_FF { get; set; }
        public Nullable<int> REG_NR_FF { get; set; }
        public Nullable<int> FRT_TOT_NR { get; set; }
        public string PLUS { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public Nullable<int> X { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
