//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGJALD2
    {
        public int Id { get; set; }
        public Nullable<int> LG_NR { get; set; }
        public Nullable<int> NR { get; set; }
        //public Nullable<int> FK_P100_Id { get; set; }
        public Nullable<decimal> U1 { get; set; }
        public Nullable<decimal> U2 { get; set; }
        public Nullable<decimal> U3 { get; set; }
        public Nullable<decimal> U4 { get; set; }
        public Nullable<decimal> U5 { get; set; }
        public Nullable<decimal> U6 { get; set; }
        public Nullable<decimal> U7 { get; set; }

        public string StarvId { get; set; }
        public int? PostNrPostnr { get; set; }
        public string LsLagId { get; set; }

        //public virtual Member P100 { get; set; }
    }
}
