//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_HOVD
    {
        public int LO_HOVD_Id { get; set; }
        public Nullable<int> LO_NR { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public Nullable<int> FK_REIDARI_Id { get; set; }
        public string SKIB_ID { get; set; }
        public Nullable<int> FK_SKIB_Id { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> ANT_LN_TXT { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public Nullable<decimal> KR_IALT_A { get; set; }
        public Nullable<decimal> KR_IALT_F { get; set; }
        public Nullable<decimal> KR_IALT_FRT { get; set; }
        public Nullable<int> SK_A { get; set; }
        public Nullable<int> KO_A { get; set; }
        public Nullable<int> SK_FR { get; set; }
        public Nullable<int> KO_FR { get; set; }
        public Nullable<int> MANS_IALT { get; set; }
        public string SKEI { get; set; }
        public Nullable<System.DateTime> UT_DATO { get; set; }
        public string UT_HH { get; set; }
        public string UT_MM { get; set; }
        public string UT_ID { get; set; }
        public Nullable<int> UT_ANT { get; set; }
    
        public virtual REIDARI REIDARI { get; set; }
        public virtual SKIB SKIB { get; set; }
    }
}
