//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_LINE
    {
        public int LO_LINE_Id { get; set; }
        public Nullable<int> LO_NR { get; set; }
        public Nullable<int> PERS_NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> ANT_LN_TXT { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public Nullable<decimal> KR_A { get; set; }
        public Nullable<decimal> KR_F { get; set; }
        public Nullable<int> SK_P { get; set; }
        public Nullable<int> KO_P { get; set; }
        public Nullable<decimal> KR_FRT { get; set; }
        public Nullable<int> SK_F { get; set; }
        public Nullable<int> KO_F { get; set; }
        public Nullable<System.DateTime> FODT { get; set; }
        public Nullable<int> CPR { get; set; }
        public Nullable<int> ARB_NR { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
