//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSLAG
    {
        public LSLAG()
        {
            this.G100 = new HashSet<G100>();
            this.P100 = new HashSet<Member>();
            //this.SBs = new HashSet<SB>();
        }

        public int LSLAG_Id { get; set; }
        public string Code { get; set; }
        public string TEKSTUR { get; set; }
        public string STUTT { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string BREV_UT { get; set; }
        public string FLYTAST { get; set; }
        public string DLISTA { get; set; }
        public string BLISTA { get; set; }
        public string ARS_LISTI { get; set; }
    
        public virtual ICollection<G100> G100 { get; set; }
        public virtual ICollection<Member> P100 { get; set; }
        //public virtual ICollection<SB> SBs { get; set; }
    }
}
