//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINLON
    {
        public int MINLON_Id { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public Nullable<decimal> PR_MD { get; set; }
        public Nullable<decimal> PR_DG { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        
        public decimal? DG_MIN { get; set; }
        public decimal? DG_MAX { get; set; }
        public decimal? GRAD { get; set; }
        public decimal? DG_ST { get; set; }

        public string KOTA { get; set; }
    }
}
