//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class P100
    {
        public P100()
        {
            this.ADRESSes = new HashSet<ADRESS>();
            this.DEB_CON = new HashSet<DEB_CON>();
            this.FRT_HOVD = new HashSet<FRT_HOVD>();
            this.FRT_LON = new HashSet<FRT_LON>();
            this.frt_lon7 = new HashSet<frt_lon7>();
            this.LGJALDs = new HashSet<LGJALD>();
            this.LGJALD2 = new HashSet<LGJALD2>();
            this.LO_LINE = new HashSet<LO_LINE>();
            this.MA_LINE = new HashSet<MA_LINE>();
            this.MI_HOVD = new HashSet<MI_HOVD>();
            this.MI2_HOVD = new HashSet<MI2_HOVD>();
            this.P1_NOT = new HashSet<P1_NOT>();
            this.P400 = new HashSet<P400>();
            this.PTXTs = new HashSet<PTXT>();
            this.SKIPMen = new HashSet<SKIPMAN>();
            this.TLF_IN = new HashSet<TLF_IN>();
            this.TRANS_P = new HashSet<TRANS_P>();
            this.TRANSPRTs = new HashSet<TRANSPRT>();
            this.UM_LINE = new HashSet<UM_LINE>();
        }

        public int Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<System.DateTime> FODT { get; set; }
        public string FNAVN { get; set; }
        public string ENAVN { get; set; }
        public string ADR1 { get; set; }
        public Nullable<int> POSTNR { get; set; }
        public Nullable<int> FK_LIMART_Id { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string FN5 { get; set; }
        public string STRIKA { get; set; }
        public string KYN { get; set; }
        public Nullable<int> PRI_OWN { get; set; }
        public Nullable<int> BETALER { get; set; }
        public string EN5 { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string M_STATUS { get; set; }
        public Nullable<int> TXT_LN { get; set; }
        public Nullable<int> TLF_HEIMA { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string ENFO { get; set; }
        public Nullable<int> CPR { get; set; }
        public string STARV { get; set; }
        public Nullable<int> FK_STARV_Id { get; set; }
        public Nullable<decimal> BURT_DG { get; set; }
        public Nullable<decimal> TUR_IALT { get; set; }
        public Nullable<decimal> INN_IALT { get; set; }
        public string DG { get; set; }
        public string MD { get; set; }
        public string STAT { get; set; }
        public Nullable<int> FK_TURHEAD_Id { get; set; }
        public Nullable<System.DateTime> TXT_DATO { get; set; }
        public Nullable<System.DateTime> LAST_DATO { get; set; }
        public string MNAVN { get; set; }
        public Nullable<int> MI_TOT { get; set; }
        public Nullable<int> LG_TOT { get; set; }
        public string MI_AR { get; set; }
        public string MI_ID { get; set; }
        public string LG_AR { get; set; }
        public Nullable<decimal> LG_KR { get; set; }
        public string LAST_ID { get; set; }
        public Nullable<System.DateTime> ETI_DATO { get; set; }
        public string ETI_HH { get; set; }
        public string ETI_MM { get; set; }
        public string ETI_ID { get; set; }
        public string SLAG { get; set; }
        public Nullable<int> FK_LSLAG_Id { get; set; }
        public Nullable<decimal> TRANSPORT { get; set; }
        public Nullable<decimal> LG_IALT { get; set; }
        public Nullable<int> LAST_KONTO { get; set; }
        public Nullable<int> LAST_REG { get; set; }
        public string FKOTA { get; set; }
        public string LAND { get; set; }
    
        public virtual ICollection<ADRESS> ADRESSes { get; set; }
        public virtual ICollection<DEB_CON> DEB_CON { get; set; }
        public virtual ICollection<FRT_HOVD> FRT_HOVD { get; set; }
        public virtual ICollection<FRT_LON> FRT_LON { get; set; }
        public virtual ICollection<frt_lon7> frt_lon7 { get; set; }
        public virtual ICollection<LGJALD> LGJALDs { get; set; }
        public virtual ICollection<LGJALD2> LGJALD2 { get; set; }
        public virtual LIMART LIMART { get; set; }
        public virtual ICollection<LO_LINE> LO_LINE { get; set; }
        public virtual LSLAG LSLAG { get; set; }
        public virtual ICollection<MA_LINE> MA_LINE { get; set; }
        public virtual ICollection<MI_HOVD> MI_HOVD { get; set; }
        public virtual ICollection<MI2_HOVD> MI2_HOVD { get; set; }
        public virtual ICollection<P1_NOT> P1_NOT { get; set; }
        public virtual STARV STARV1 { get; set; }
        public virtual TURHEAD TURHEAD { get; set; }
        public virtual ICollection<P400> P400 { get; set; }
        public virtual ICollection<PTXT> PTXTs { get; set; }
        public virtual ICollection<SKIPMAN> SKIPMen { get; set; }
        public virtual ICollection<TLF_IN> TLF_IN { get; set; }
        public virtual ICollection<TRANS_P> TRANS_P { get; set; }
        public virtual ICollection<TRANSPRT> TRANSPRTs { get; set; }
        public virtual ICollection<UM_LINE> UM_LINE { get; set; }
    }
}
