//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class P400
    {
        public int P400_Id { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> FK_P100_Id { get; set; }
        public string FNAVN { get; set; }
        public string ENAVN { get; set; }
        public Nullable<int> POST { get; set; }
        public Nullable<decimal> KR { get; set; }
        public string ART { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public Nullable<System.DateTime> UD_DATO { get; set; }
        public string UD_HH { get; set; }
        public string UD_MM { get; set; }
        public string UD_ID { get; set; }
        public Nullable<int> REG { get; set; }
        public Nullable<int> KONTO { get; set; }
    
        public virtual Member P100 { get; set; }
    }
}
