//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTNR
    {
        public int Id { get; set; }
        public string PostalCode { get; set; }
        public string BYGD { get; set; }
        //public Nullable<int> MEDL_IALT { get; set; }
        //public Nullable<int> MEDL_HAN { get; set; }
        //public Nullable<int> MEDL_HUN { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string BYKEY { get; set; }
        public int ANTAL { get; set; }
        public string LAND { get; set; }
        public int ANT_K { get; set; }
        public int ANT_M { get; set; }
        public int ANT_X { get; set; }
        public int KOMNR { get; set; }
        public int OKI { get; set; }
        public int FAX_SP { get; set; }
        public int FAX_FB { get; set; }
        public int FAX_SJ { get; set; }
        public int FAX_F { get; set; }
    }
}
