//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class REIDARI
    {
        public REIDARI()
        {
            this.LO_HOVD = new HashSet<LO_HOVD>();
            this.P200 = new HashSet<P200>();
            this.ADRESSes = new HashSet<ADRESS>();
            this.SKIBs = new HashSet<SKIB>();
            this.SKIPs = new HashSet<SKIP>();
            this.TR_HOVD1 = new HashSet<TR_HOVD>();
        }
    
        public int REIDARI_Id { get; set; }
        public string RE_NUMMER { get; set; }
        public string TLF { get; set; }
        public string FOEN { get; set; }
        public string FNAVN { get; set; }
        public string ENAVN { get; set; }
        public string ADR_1 { get; set; }
        public string ADR_2 { get; set; }
        public Nullable<int> POSTNR { get; set; }
        public Nullable<int> FK_TR_HOVD_Id { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
    
        public virtual ICollection<LO_HOVD> LO_HOVD { get; set; }
        public virtual ICollection<P200> P200 { get; set; }
        public virtual TR_HOVD TR_HOVD { get; set; }
        public virtual ICollection<ADRESS> ADRESSes { get; set; }
        public virtual ICollection<SKIB> SKIBs { get; set; }
        public virtual ICollection<SKIP> SKIPs { get; set; }
        public virtual ICollection<TR_HOVD> TR_HOVD1 { get; set; }
    }
}
