//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class STARV
    {
        public STARV()
        {
            this.G100 = new HashSet<G100>();
            this.P100 = new HashSet<Member>();
            this.SBs = new HashSet<SB>();
            this.STXSKs = new HashSet<STXSK>();
            this.TURHEADs = new HashSet<TURHEAD>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string TEKSTUR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public string TEKSTUR2 { get; set; }
        public string STUTT { get; set; }
        public string TXT5 { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public Nullable<int> ANTAL { get; set; }
        public Nullable<System.DateTime> TAL_DATO { get; set; }
        public string TAL_HH { get; set; }
        public string TAL_MM { get; set; }
        public string TAL_ID { get; set; }
        public Nullable<decimal> PART { get; set; }
        public Nullable<decimal> TIL_DG { get; set; }
        public Nullable<decimal> TIL_TUR { get; set; }
        public string FELAG { get; set; }
        public string FKOTA { get; set; }
        public string ALKA { get; set; }
    
        public virtual ICollection<G100> G100 { get; set; }
        public virtual ICollection<Member> P100 { get; set; }
        public virtual ICollection<SB> SBs { get; set; }
        public virtual ICollection<STXSK> STXSKs { get; set; }
        public virtual ICollection<TURHEAD> TURHEADs { get; set; }
    }
}
