//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDART
    {
        //public STUDART()
        //{
        //    this.STUDPRIS = new HashSet<STUDPRI>();
        //    this.STXFIs = new HashSet<STXFI>();
        //}
    
        public int ID { get; set; }
        public string StudArtCode { get; set; }
        public string NAVN { get; set; }
        public string STUTT { get; set; }
        public string ALIAS { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> LINK { get; set; }
        public string RAD { get; set; }
        public string TYPA { get; set; }
    
        //public virtual ICollection<STUDPRI> STUDPRIS { get; set; }
        //public virtual ICollection<STXFI> STXFIs { get; set; }
    }
}
