//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapWebApplication.Models.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_HOVD
    {
        public TR_HOVD()
        {
            this.FR_LINE = new HashSet<FR_LINE>();
            this.LINEs = new HashSet<LINE>();
            this.MA_LINE = new HashSet<MA_LINE>();
            this.MANNINGs = new HashSet<MANNING>();
            this.MI_HOVD = new HashSet<MI_HOVD>();
            this.MI2_HOVD = new HashSet<MI2_HOVD>();
            this.REIDARIs = new HashSet<REIDARI>();
            this.TR_KRED = new HashSet<TR_KRED>();
            this.TR_LINE = new HashSet<TR_LINE>();
            this.TR_STUD = new HashSet<TR_STUD>();
            this.TR_STUDM = new HashSet<TR_STUDM>();
            this.TR_STUDS = new HashSet<TR_STUDS>();
            this.TR_TXT = new HashSet<TR_TXT>();
            this.TRANS_TR = new HashSet<TRANS_TR>();
        }
    
        public int TR_HOVD_Id { get; set; }
        public string ID_SKIB { get; set; }
        public Nullable<int> FK_SKIB_Id { get; set; }
        public int? ID_TUR { get; set; }
        public Nullable<System.DateTime> FRA_DATO { get; set; }
        public Nullable<System.DateTime> TIL_DATO { get; set; }
        public Nullable<int> TR_NR { get; set; }
        public string PAR_SKIP { get; set; }
        public Nullable<int> PAR_SKJAL { get; set; }
        public Nullable<decimal> MANNING { get; set; }
        public string AVR_STAD { get; set; }
        public Nullable<int> FK_P600_Id { get; set; }
        public string SK_ID { get; set; }
        public Nullable<System.DateTime> OPR_DATO { get; set; }
        public string OPR_HH { get; set; }
        public string OPR_MM { get; set; }
        public string OPR_ID { get; set; }
        public string STATUS { get; set; }
        public string UDSKREVET { get; set; }
        public string UPPTALD { get; set; }
        public Nullable<System.DateTime> UD_DATO { get; set; }
        public string UD_HH { get; set; }
        public string UD_MM { get; set; }
        public string UD_ID { get; set; }
        public Nullable<decimal> KG_IALT { get; set; }
        public Nullable<decimal> UPPH_IALT { get; set; }
        public Nullable<decimal> TIL_SKIP_PCT { get; set; }
        public Nullable<decimal> TIL_SKIP_KR { get; set; }
        public Nullable<decimal> TIL_MANN_PCT { get; set; }
        public Nullable<decimal> TIL_MANN_KR { get; set; }
        public Nullable<int> LOBNR { get; set; }
        public string VIDAR { get; set; }
        public Nullable<System.DateTime> RET_DATO { get; set; }
        public string RET_HH { get; set; }
        public string RET_MM { get; set; }
        public string RET_ID { get; set; }
        public Nullable<int> LN_IALT { get; set; }
        public Nullable<int> ANT_LN_TXT { get; set; }
        public Nullable<int> TUR_NR { get; set; }
        public Nullable<System.DateTime> AVR_DATO { get; set; }
        public Nullable<decimal> DAGAR { get; set; }
        public Nullable<int> ID_REDERI { get; set; }
        public Nullable<int> FK_REIDARI_Id { get; set; }
        public Nullable<decimal> MANNING_I { get; set; }
        public Nullable<decimal> SKIP_STUD { get; set; }
        public Nullable<decimal> MAN_STUD { get; set; }
        public Nullable<decimal> TILSKOT { get; set; }
        public Nullable<decimal> FRADRAG { get; set; }
        public Nullable<decimal> TIL_MANN_TOT { get; set; }
        public Nullable<decimal> FRADRAG2 { get; set; }
        public Nullable<decimal> MANN_PART { get; set; }
        public Nullable<decimal> PR_DAG { get; set; }
        public Nullable<decimal> MINLON { get; set; }
        public Nullable<decimal> DAGLON { get; set; }
        public string SKIB_TXT { get; set; }
        public Nullable<decimal> TOTAL_KR { get; set; }
        public Nullable<decimal> MANN_PART_IS { get; set; }
        public Nullable<int> MID_AR { get; set; }
        public Nullable<decimal> MANN_PART_I { get; set; }
        public Nullable<int> ARB_NR { get; set; }
        public string PAR_ART { get; set; }
        public string PAR_TUR_ID { get; set; }
        public Nullable<decimal> MANNING_X { get; set; }
        public string ALT_MP { get; set; }
        public Nullable<int> ALT_MA { get; set; }
        public string CHECK { get; set; }
        public Nullable<int> TRYG_ANT { get; set; }
        public Nullable<decimal> TRYG_KR { get; set; }
        public Nullable<decimal> TRYG_KRHB { get; set; }
        public string TRYG_KVIT { get; set; }
        public Nullable<int> TRYG_BILAG { get; set; }
        public Nullable<System.DateTime> TRYG_DATO { get; set; }

        public int? ReidariId { get; set; }
        public string SkipId { get; set; }
        public int? TypaId { get; set; }
        public int? PostNrId { get; set; }
    
        public virtual ICollection<FR_LINE> FR_LINE { get; set; }
        public virtual ICollection<LINE> LINEs { get; set; }
        public virtual ICollection<MA_LINE> MA_LINE { get; set; }
        public virtual ICollection<MANNING> MANNINGs { get; set; }
        public virtual ICollection<MI_HOVD> MI_HOVD { get; set; }
        public virtual ICollection<MI2_HOVD> MI2_HOVD { get; set; }
        public virtual P600 P600 { get; set; }
        public virtual ICollection<REIDARI> REIDARIs { get; set; }
        public virtual REIDARI REIDARI { get; set; }
        public virtual SKIB SKIB { get; set; }
        public virtual ICollection<TR_KRED> TR_KRED { get; set; }
        public virtual ICollection<TR_LINE> TR_LINE { get; set; }
        public virtual ICollection<TR_STUD> TR_STUD { get; set; }
        public virtual ICollection<TR_STUDM> TR_STUDM { get; set; }
        public virtual ICollection<TR_STUDS> TR_STUDS { get; set; }
        public virtual ICollection<TR_TXT> TR_TXT { get; set; }
        public virtual ICollection<TRANS_TR> TRANS_TR { get; set; }
    }
}
